### ISSUE TITLE
Unable to delete Location or Item

### ISSUE THREAD

**Issue by Surgical71** [hay-kot/homebox#104]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Latest

### What is the issue you are experiencing?

Unable to delete any Location or Item that was created

### How can the maintainer reproduce the issue?

Try and delete an Item

### Deployment

Docker (Linux)

**Comment by Surgical71** [comment]
No Longer an Issue. Had to refresh browser and then click Delete again for it to work. Might just be my Browser that's the issue

**Comment by deranjer** [comment]
FYI, just had the exact same issue, no response from button unless I refreshed the page.  Using Brave browser (chrome based).
