### ISSUE TITLE
Feature: Tree View for Location/Item based viewer. 

### ISSUE THREAD

**Issue by TheChrisTech** [hay-kot/homebox#139]
### What is the problem you are trying to solve with this feature?

As a user I would like the ability visually inspect storage locations, without the need to navigate to multiple pages before getting to a specific box. This request should also improve the dropdown locations within menus to be better navigable, based on the nested hierarchy. 

### What is the solution you are proposing?

For the standard location on the main page, maybe something like this?
![image](https://user-images.githubusercontent.com/32913587/201202042-aa377e34-4574-4f22-b488-9cf141fb2b57.png)

For the items page, the dropdown nesting similar to this?
![image](https://user-images.githubusercontent.com/32913587/201202477-f203da2e-d6ca-4231-a558-7b98b6740ffd.png)

### Additional context

Screenshots above were taken from my inventory project I was working on (but don't have time for anymore). I'm more than happy to share some code, but it'd in .php (which I'm no expert in).  I unfortunately do not have GO experience.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Any thoughts on how to visually distinguish the difference between locations with Children and those without? In the image below Computer and Root have children, but the rest don't and I don't feel like that's visually very clear.

<img width="292" alt="CleanShot 2023-01-27 at 11 21 41@2x" src="https://user-images.githubusercontent.com/64056131/215189874-9054d5f3-70bb-4d37-a58f-b11460c2119f.png">

**Comment by TheChrisTech** [comment]
I think the side caret is enough to distinguish if there’s children or not. For easier editing, maybe make a button after (or a ‘…’) button to drop down a menu (add child, edit, delete)?

**Comment by icsy7867** [comment]
I am not sure if the brackets can be clicked and then the children show?  Or are some of the other items their children?

The unicode triangle looks pretty good I think (Although github renders them differently.  But these can be stored in the sql database without issue, and show up in homebox like a plain black triangle.

Programmatically... If these are already in an order where a child and sub childrent are underneath their parent.  Some simple spacing and unicode symbol might be easier, and should be easy to change in javascript.

Assuming you can make a function to count how many parents above it (So Child 1 and Child 2 have 1 parent above it, and Sub-Child 1 and Sub-Child 2 have 2 parents above it).  You could add some simple spaces.  In this example, for every parent above the child, you add 3 spaces.

And then each child includes a unicode triangle arrow (Could also use a boot strap icon or something similar: https://icons.getbootstrap.com/icons/arrow-right/)

Parent
   ▶ Child 1
   ▶ Child 2
      ▶ Sub-Child 1
      ▶ Sub-Child 2  

Also including a screenshot as github will change this particular unicode character:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/3788162/215192588-a9de7b1c-2195-4d18-b99a-30c6e85a4965.png">

So mathematically...

Parent [0 parents above, no space and no spaces or arrow]
   ▶ Child 1 [1 parent above, so x3 spaces and arrow]
   ▶ Child 2 [1 parent above, so x3 spaces and arrow]
      ▶ Sub-Child 1 [2 parents above, so 2x(x3) spaces (6 spaces total) and arrow]
      ▶ Sub-Child 2  [2 parents above, so 2x(x3) spaces (6 spaces total) and arrow]

The benefit here is nothing on the backend is really changing, other than needing to know how many parents above there are.  And that the locations are listed in the correct order.

There are some other good examples around too:
https://www.jqueryscript.net/table/Minimal-Tree-Table-jQuery-Plugin-For-Bootstrap-TreeTable.html

My javascript is limited.  Currently I am just naming my parent and sub locations like:
Parents ▶ Child ▶ Sub-child

But this gets messy when going through various locations.

**Comment by hay-kot** [comment]
I updated the screenshot to show an example of the tree expanded

**Comment by icsy7867** [comment]
> I think the side caret is enough to distinguish if there’s children or not. For easier editing, maybe make a button after (or a ‘…’) button to drop down a menu (add child, edit, delete)?

This little GPS Icons are nice! You could also change the icon for the items with children to a plug icon:
https://icons.getbootstrap.com/icons/plus-square/ or something just to add a little difference, if that doesnt make it all look too busy.

However, knowing the carats are there and the drop downs have been implemented, it is probably sufficient! I like homebox a lot due to how simple and clean it is.

**Comment by hay-kot** [comment]
See 

- https://github.com/hay-kot/homebox/pull/248

for implementation details and examples of the new UI

**Comment by hay-kot** [comment]
> It's pretty nice - unfortunately this view seems to appear only when editing an item and not when creating a new one.

I don't understand what this means

**Comment by hay-kot** [comment]
@AmineI oooohhhhhh. I missed that one, thanks!
 
Fixed in

- #252
