### ISSUE TITLE
Per item currency

### ISSUE THREAD

**Issue by wazabees** [hay-kot/homebox#140]
### What is the problem you are trying to solve with this feature?

Would it be possible to implement per item currency selection? I buy things from all over the place, in USD, EUR, etc.

### What is the solution you are proposing?

When adding an item, a dropdown selection of currencies would be preferred. Base/profile currency should be used by default.

### What alternatives have you considered?

Alternative would be to just use the converted value of the base/profile currency.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Thanks for the idea. I don't think this is something I want to handle inside the application. In the future I'd like to implement some custom reporting like features that would work directly with the currencies. Keeping them all the same for a group helps immensely in managing complexity in the code base by not having to worry about mixed currencies.

I think that it's going to be up to the user to do the conversion at the time of purchase to the base currency of their choice.

**Comment by arthurmv** [comment]
It would be very handy for me too, I live near of the border, and buy things in USD and MXN.

**Comment by dominch** [comment]
I also would love to get such feature, living in modern world require to handle more than one currency sooner or later. If You buy something at ali, amazon, ebay and local services like olx, allegro You just get mixed currencies for some of items.  Of course this leds to problem when some of currencies will be mixed on lists, but this also can be solved and still it's much better than to recalc everything on add.
