### ISSUE TITLE
Feature:: Hide all empty fields

### ISSUE THREAD

**Issue by InsaneSplash** [hay-kot/homebox#144]
### What is the problem you are trying to solve with this feature?

Hide all fields that do not contain any data.

### What is the solution you are proposing?

To hide any fields that are empty and to not automatically include a default warranty date.

Example Warranty Information.

### What alternatives have you considered?

None

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by BCNelson** [comment]
This appears to be fix in nightly

**Comment by timdonovanuk** [comment]
Is there a regression or am I misunderstanding this feature?

On the demo site this doesn't function:

![image](https://github.com/hay-kot/homebox/assets/8156439/b4e51abf-d645-487e-84b5-7f44bda0a481)

**Comment by timdonovanuk** [comment]
Ignore, I just saw the show-empty toggle staring me in the face ;)
