### ISSUE TITLE
Export CSV? of database

### ISSUE THREAD

**Issue by operatort** [hay-kot/homebox#147]
### What is the problem you are trying to solve with this feature?

Should the Database break or you move to another instance, an export feature would be usefull
The import feature seem to already excist.

Great App so far :)

### What is the solution you are proposing?

CSV Export function and button

### What alternatives have you considered?

none

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
We're planning out implementing that! Closing since there's already a task for this.  

- https://github.com/hay-kot/homebox/issues/16
