### ISSUE TITLE
Add user defined fields to locations

### ISSUE THREAD

**Issue by majant0** [hay-kot/homebox#155]
### What is the problem you are trying to solve with this feature?

I would like to see user defined fields added to the Locations. Currently, the exist only on the Items.

### What is the solution you are proposing?

Adding user defined fields to the Location screen.

### What alternatives have you considered?

Given what I said in the "Additional context" field below, if a more built-in solution for storing home inventory videos is preferred, then I would support that as well.

### Additional context

I plan on recording a [home inventory video](https://www.hippo.com/blog/valuable-5-minute-video-youll-ever-make) for each room and I'd like to store the link to that video in a field on the Location entry.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Sorry I haven't followed up here. 

I don't see value in providing custom fields for locations (though I could be convinced). However I can totally see wanting to upload images of a location so I think adding attachments is something I'd be willing to implement.

**Comment by majant0** [comment]
My only concern with attachments is that I'd like to do a video, and that could result in a large file. But, yes, attachments would at least be a step in the right direction.

Thanks.

**Comment by hay-kot** [comment]
@majant0 - any reason you couldn't use the markdown field (description) on the locations? Someone brought that up in the discord, and I think given the limited use cases for custom fields on locations it might be a good option here?

**Comment by majant0** [comment]
Just upgraded to 0.7. Yes, I can make it work with the markdown support.
Thanks!
