### ISSUE TITLE
Add languge and currency support for Chinese please

### ISSUE THREAD

**Issue by zhanghengtian** [hay-kot/homebox#157]
### What is the problem you are trying to solve with this feature?

Add languge and currency support for Chinese please.

Please add currency: RMB CNY ( Chinese Yuan)
add Chinese language support will be great.

### What is the solution you are proposing?

Add languge and currency support for Chinese please.

Please add currency: RMB CNY ( Chinese Yuan)
add Chinese language support will be great.

### What alternatives have you considered?

Add languge and currency support for Chinese please.

Please add currency: RMB CNY ( Chinese Yuan)
add Chinese language support will be great.

### Additional context

Add languge and currency support for Chinese please.

Please add currency: RMB CNY ( Chinese Yuan)
add Chinese language support will be great.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by jpbaril** [comment]
@hay-kot Any plans of making Homebox multilingual ?

**Comment by yacinegithub** [comment]
@hay-kot multilangue is a must for such good app thank you.
