### ISSUE TITLE
Unablee to use the Discord Invite

### ISSUE THREAD

**Issue by InsaneSplash** [hay-kot/homebox#164]
### What is the problem you are trying to solve with this feature?

It seems that the Discord invite is no longer working.

### What is the solution you are proposing?

Provide a new invite link. :)

### Additional context

https://discord.com/invite/tuncmNrE4z

![image](https://user-images.githubusercontent.com/16985649/205387288-915be1a0-02e0-4d80-ab3a-e76893f8433e.png)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
🤷 Seems to be working fine for me, I tried updating the link but it spat out the same one. Maybe give it another go? Could have been a problem with discord
