### ISSUE TITLE
BaseURL environment option

### ISSUE THREAD

**Issue by CTParkinson** [hay-kot/homebox#179]
### What is the problem you are trying to solve with this feature?

Cannot run at `example.com/homebox` as it then cannot load assets.

### What is the solution you are proposing?

Allow setting of a baseUrl in the environment variables so that when hosted at a folder on a domain the app's assets can be loaded and it can access it's own API endpoints correctly.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't believe this is possible to provide at runtime with how we have Vue setup. Happy to accept a PR that will work for both use cases, but I'm fairly certain this is not possible without someone manually downloading the repository and building the frontend themselves.
