### ISSUE TITLE
Table view for Items

### ISSUE THREAD

**Issue by guigui42** [hay-kot/homebox#184]
### What is the problem you are trying to solve with this feature?

I want to be able to search and filter easily all my "things"

### What is the solution you are proposing?

A table view  to list all my items, where I can order by **price tag,** or **manufacturer** easily.

### What alternatives have you considered?

Excel is the alternative to do that.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Yeah, I'd love to support this. Happy to accept a PR. Will be some time before I get around to the table implementation.

**Comment by hay-kot** [comment]
Closing this issue and tracking in #265 where I've fleshed out some more details so we can track incremental implementation of this.

**Comment by Dxvxdffm** [comment]
Would be nice to be able to choose the amount of items shown per page in the table view.
For example:
- 10 Items
- 50 Items
- 100 Items
- All items
or something like this. Just 10 items are a bit less in the table view as it is right now.
![image](https://user-images.githubusercontent.com/70025707/218314468-4f9f6bc5-059a-47a2-960d-c714f05c9c1b.png)
