### ISSUE TITLE
Add a picture to an item

### ISSUE THREAD

**Issue by wallace11** [hay-kot/homebox#187]
Because sometimes words aren't enough to describe an item :)

Also, it'd make scrolling through many items much easier.

**Comment by PinguCloud** [comment]
You can edit a picture in the extended view while editing an item.

**Comment by wallace11** [comment]
Is the demo instance updated?
I judged by it when opening this issue

**Comment by hay-kot** [comment]
You absolutely can already do this. Please review the attachments area on the edit page. Currently there is no gallery to view images in-browser but that has already been added for the next release.

Thanks!
