### ISSUE TITLE
[Task] - Admin Panel

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/homebox#19]
## Description

Currently there is no mechanism for administrators to manage any data from the GUI. 

## Feature Set 

- [ ] First registered user should default to an admin
- [ ] Instance Statistics
- [ ] User Management
  - [ ] Delete User
  - [ ] Reset Password

**Comment by hay-kot** [comment]
I don't see much of a need for this. I may revisit but closing for now

**Comment by n00b12345** [comment]
An easy way to view all users would be really nice. Even if not an admin panel, at least the ability to view all registered users would be great.

Thank you for creating homebox. It's great!

**Comment by Bjorkan** [comment]
> An easy way to view all users would be really nice. Even if not an admin panel, at least the ability to view all registered users would be great.
> 
> Thank you for creating homebox. It's great!

I agree aswell! One of few features that I miss from this fantastic software! Just being able to see users, invites and manage the instance would be lovely! <3
