### ISSUE TITLE
Barcode generator and scanner - like barcode buddy

### ISSUE THREAD

**Issue by MrPresident2** [hay-kot/homebox#191]
### What is the problem you are trying to solve with this feature?

the ability to generate and print barcodes and get information or do actions by scanning the barcode

### What is the solution you are proposing?

implementing or adding something like barcode buddy to homebox

### Additional context

I think its one of the most important features of a storage app, So let's say I have a few box storage in my garage, by scanning the barcode I can see all the things inside that box, more than that, barcode buddy also lets you take something out of the inventory or add it but scanning of the barcode again.

This is barcode buddy: https://github.com/Forceu/barcodebuddy

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by rafaelmathieu** [comment]
that would be great, I would add to this saying that a QR code generator would be great. that can be printer and put on boxes.

**Comment by hay-kot** [comment]
I'm currently working on a QR Code feature now, but I'm not sure that Homebox needs to own the barcode feature when QR codes let us lean on smartphones to handle the scanning and displaying of information. I'd imagine 99% of the time you'd just want to scan the barcode and be redirected to the location or items page. 

@MrPresident2, would QR codes fill the void here, or is there a use case I'm missing?

**Comment by hay-kot** [comment]
See 

- https://github.com/hay-kot/homebox/issues/227 

for QR Code discussion

**Comment by MrPresident2** [comment]
> 

Yes, there is a huge use case that you're missing. (We are using Barcode Body on different project Grocy) but it is not for storage, and we are missing a project for storage management. That's why we are all excited about this project.
The idea is that you can use your phone to do 3 main jobs with that barcode.

First: let's say you have a storage room with many boxes, you can scan the barcode on one of the boxes and get the information about each and every product inside of the box, without the need to open a web browser.  

Second Use: will be to scan the product you need, and while scanning it will automatically remove that one from the storage so if you had 1 in the box, after the scan you have 0 in the box.

Third: if you get the same product again, by scanning its barcode again you will add it back to the inventory.

Grocy does it with Barcode Body and it's working great. Something like that will make this project the one and only project we will need for home storage management

**Comment by hay-kot** [comment]
> First: let's say you have a storage room with many boxes, you can scan the barcode on one of the boxes and get the information about each and every product inside of the box, without the need to open a web browser.

This use case will be covered by QR codes. Scanning the code will take you to the webpage and you can see what items are inside the location and make edits if necessary.

> Second Use: will be to scan the product you need, and while scanning it will automatically remove that one from the storage so if you had 1 in the box, after the scan you have 0 in the box.

My personal opinion is that this type of inventory management if a lofty goal that is solemnly used by people, especially with household goods. Additionally, Homebox's primary purpose falls outside of this use case IMO. It's not really meant for consumables as much as it is meant for Electronics, Expensive Items, or Household Appliances. This feature feels more of a business facing feature than a consumer one. 

> Third: if you get the same product again, by scanning its barcode again you will add it back to the inventory.

Same answer as the above. 

--- 

Even if these were within what I would consider as the scope, I don't think that doing this via a web application would be a good user experience. You'd really want a native application with better Camera/Scanner integrations. Creating the sort of experience your describing with a web app would be kind of a pain, and I won't be working on a mobile app for Homebox unless it is directly sponsored work. 

Given that the primary use case of Printable QR codes will be covered, I'm going to consider _this_ issue closed once that work is complete. 

@MrPresident2 - You're welcome to flesh out another feature request with your specific asks, screenshots or mock-ups and request some community feedback on the feature. If it get's enough traction we may revisit the possibility of implementing some of those in-depth scanning features.

**Comment by Serios** [comment]
> Even if these were within what I would consider as the scope, I don't think that doing this via a web application would be a good user experience. You'd really want a native application with better Camera/Scanner integrations. Creating the sort of experience your describing with a web app would be kind of a pain, and I won't be working on a mobile app for Homebox unless it is directly sponsored work.


While I agree with you, there are very nice JS libraries which can be implemented [html5-qrcode](https://github.com/mebjas/html5-qrcode), [quaggaJS](https://github.com/serratus/quaggaJS) for bringing native functionality for scanning codes, since the native code scanning ability especially on Android devices without an app is a crap. In my company we are using WebApp which uses html5-qrcode library and is working great. In that way there is no need for developing separate mobile app.

> My personal opinion is that this type of inventory management if a lofty goal that is solemnly used by people, especially with household goods. Additionally, Homebox's primary purpose falls outside of this use case IMO. It's not really meant for consumables as much as it is meant for Electronics, Expensive Items, or Household Appliances. This feature feels more of a business facing feature than a consumer one.

If it is a very simple inventory management, eg. just increasing/decreasing quantities of the items, in #227 you can see N:3 in my comment for a simple implementation of this, I don't think will be so lofty goal. 

For an personal example - I'm using HB, except for organizing other things, for storing info for some electronic components for my DIY projects too and currently is a real pain when I want to increase/decrease the quantities of batteries, small ic board or couple of resistors etc. I know there are some other solutions specially made for inventory management of electronic components but the are overly complicated for a guy, that twice a year will cobble something for 30 min in his garage. I think others can give similar examples too.

**Comment by hay-kot** [comment]
Closing since the initial work for QR label printing is done ([see above](https://github.com/hay-kot/homebox/issues/191#issuecomment-1407788210))

Also to reiterate

> You're welcome to flesh out another feature request with your specific asks, screenshots or mock-ups and request some community feedback on the feature. If it get's enough traction we may revisit the possibility of implementing some of those in-depth scanning features.
