### ISSUE TITLE
[Task] - Implement a Dev Container for Contrubutors

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/homebox#20]
## Description

Currently HomeBox uses several dependencies to develop which could be cumbersome for new contributors. 

## Feature Set

- [ ] Development Container for Go/Vue with Taskfile pre-installed.

**Comment by Motordom** [comment]
This would be fantastic! 😄

**Comment by devotoare** [comment]
Actually just forked this to contribute but trying to work directly from the frontend is missing a couple things in the dependencies so it's not quite as fast to spin up as I'd thought. So a dockerfile for dev would be wonderful!

**Comment by hay-kot** [comment]
What's missing from the dependencies?
