### ISSUE TITLE
Add a "Create and Add New" button while creating items

### ISSUE THREAD

**Issue by Aadityajoshi151** [hay-kot/homebox#200]
### What is the problem you are trying to solve with this feature?

When I am adding multiple items to a location one after the other, it is a bit frustrating to click on the green "+create" button to add another item.

### What is the solution you are proposing?

While adding an item, on the card, a new button called "Create and Add New" button should be present right next to the create button which saves the current item and clears out all the fields so the user can start adding the next item right from there itself. This functionality can be extended while adding locations and labels too but that might be secondary. Primarily it should exist for adding items.
I am talking about the following screen:
![image](https://user-images.githubusercontent.com/46566766/211135245-baf0feaa-fedf-4dd0-86d9-c5da423c195f.png)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Any thoughts on the UI for this? I don't really want to add another button on the button with "Create and Add New" that would really clutter up the space I think. 

Once I get that figured out, I can implement this fairly easily I think.

**Comment by icsy7867** [comment]
Just tossing this out there.  You could add an additional link in a toast message.  You could either do it in the existing toast:
<img width="272" alt="image" src="https://user-images.githubusercontent.com/3788162/213841053-67827920-ff6c-4948-a08e-5baca29b6d9d.png">
Amnd provide an extra link "add new" or a simple "copy".  The 5 seconds the toast is visible should be plenty of time to click it.

Alternatively you could do two toasts.  One with the "Item created" and another with a "Click here to add new" (or something like that)  I dont think the two tiny popups in the top right corner would make a huge difference.  And they automatically disappear.  So I dont think it would impact the simplicity at all.

**Comment by Aadityajoshi151** [comment]
The ideal solution would be to add a button. I also like @icsy7867's suggestion to add a link in the toast message but according to me, it should be done in the existing toast message. 2 toasts might look a bit odd.
There is one more idea where you can add a [dropdown button](https://getbootstrap.com/docs/4.0/components/dropdowns/) where "Create and Add New" button is in present in the dropdown.
Let me know your thoughts.

**Comment by hay-kot** [comment]
@Aadityajoshi151 fantastic idea, was able to sneak this in in this branch, thanks for the idea!

- https://github.com/hay-kot/homebox/pull/235 

<img width="820" alt="CleanShot 2023-01-20 at 20 35 32@2x" src="https://user-images.githubusercontent.com/64056131/213845299-41f84698-b8ad-4052-a2c6-d43bbaf66076.png">
