### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by ThoMagnum** [hay-kot/homebox#232]
### What is the problem you are trying to solve with this feature?

If I create an Item, I only can use a dot as a separator within the price and the currency is automaticly set to $.

### What is the solution you are proposing?

A country selection for example can hel to manage different localisations like "Euro" for example and herewith the "," as a separator.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
You can choose your currency on the profile page. If your currency isn't supported you can request for it to be added, or submit a PR to add support. 

![CleanShot 2023-01-21 at 20 50 30](https://user-images.githubusercontent.com/64056131/213902613-b6cd1d82-7f44-4442-8ed9-93eed094314e.png)

I don't think it's super necessary to add support for `,` since it is going to add a lot of edge cases for what I view as a minor inconvience.

**Comment by jk** [comment]
@hay-kot I want to disagree on

> I don't think it's super necessary to add support for , since it is going to add a lot of edge cases for what I view as a minor inconvience.

True, it will introduce some edge-cases, but not very hard ones, I think. Heaps of other projects were able to tackle the exact same issue. Most ecosystems even provide libraries which abstract the chores away.

Living in a country where the `,` is the decimal separator and the point is `,` is the thousands' separator, I'm confused every time I enter a price and think that it is worth the effort to integrate such a library.

I'm not a go programmer by day, but do you consider merging a PR if start working on that feature?

**Comment by hay-kot** [comment]
> Heaps of other projects were able to tackle the exact same issue.

Do you have any specific examples?

> do you consider merging a PR if start working on that feature?

Provided there's sufficient test coverage, and any modifications support the multi-tenant architecture sure.
