### ISSUE TITLE
Default admin account?  Created initial user but seems to be missing settings

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#234]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.6.0

### What is the issue you are experiencing?

I might be missing something. I looked through the docs, and searched the issues.  I was able to make a user without trouble, but after logging in, it doesnt appear to have all the settings and options (Such as the themes) as the demo does.  Am I missing a step?  Is there a default admin user? Or can I make a user an admin?

### How can the maintainer reproduce the issue?

Make a new deployment.  Log in after creating a user.

### Deployment

Docker (Linux)

### Deployment Details

Docker via rancher/kubernetes (running on flatcar linux).

Using a traefik ingress for HTTPS access.

**Comment by icsy7867** [comment]
Actually I think I was just confused because the demo site has the twinkie (3 bars) in the top right and some other items on the dashboard.

But my local deployment is missing those items.

**Comment by hay-kot** [comment]
The demo is the nightly version, which has undergone a redesign, so it looks pretty different.

Once the next version is out, it will look closer to what's in the demo site. It's not super clear that the demo isn't the latest container though, so I get the misunderstanding.

**Comment by icsy7867** [comment]
Np, I actually was poking around your tags and had just updated my k8s deployment to your nightly.  Your handling of nested locations in the nightly much better! I will stick with the nightly for now.

My only suggestion at the moment, is when choosing a parent in the item search and filtering locations, that it shows all the items within that location.

I.E If you have a storage unit, and you have multiple sub locations and items within that storage unit.  All items within that location and child locations would show.  I.E - the SQL query would become an OR with each of the sublocations.

But great work! I am enjoying seeing all the changes.
