### ISSUE TITLE
Nested Locations (Child / Parents) should show underneath parent in selection list

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#237]
### What is the problem you are trying to solve with this feature?

Nested locations (I.E Child locations) should show up in the alphabetized drop down selection list in their Parent/Child order when either selecting a new location, or applying a location to a new item.  If i have similarly named child locations, I need to be able to tell, easily, which one is a parent.

### What is the solution you are proposing?

Child locations should appear under their parent, and alphabetized with other child.

In this list, the options should automatically appear this way without having the extra text.  I.E

The child location should just be named "Child".  And the drop down list should automatically show:
Parent ▶ Child
(The unicode character should be viewable in all browsers and storable in your sql database).

These would keep them in the proper order, while preserving alphabetizing the same tiers of children items as well without having to re-implenent the wheel.  You could also experiment with the down and right unicode arrow as well:
↳

To indicate children

### What alternatives have you considered?

As an alternative, I have simply includes the parents in the child locations name, and used a sideways triangle unicode symbol to indicate the parent/children
<img width="796" alt="image" src="https://user-images.githubusercontent.com/3788162/213897591-65702ca0-5cb9-4002-8884-942f37233c35.png">

This works well to keep items sorted/alphabetized in the correct order, however it is a bit confusing when viewing a specic location.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/3788162/213897626-840349f6-fbeb-4a81-8d25-7cfea00eb7d0.png">

### Additional context

For my specific use case, I have a storage unit with two very tall identical shelves.  One of the left and one on the right.  So If I have:

Storage Unit  ▶ Left Shelves  ▶ Row 1
Storage Unit  ▶ Right Shelves  ▶ Row 1

I need a way for "Row 1" for the left and right shelves to be in the location list while being able to identify which is which.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by icsy7867** [comment]
I agree.  Since this is more about modifying how the data is displayed in the existing dropdown list, rather than fundamentally changing the list I thought it could be a separate issue.  However, happy to close as a duplicate and add as a suggestion to #139 instead.

**Comment by hay-kot** [comment]
@icsy7867 - let's track it in #139. Lots of overlap there, thanks!
