### ISSUE TITLE
When going through locations, child items should also display.

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#238]
### What is the problem you are trying to solve with this feature?

If I have:
Home  ▶ Storage Unit  ▶ Left Shelf

(And lets say each location has 10 items)

When I click the "Home" location, I should be able to see all items in that location as well as the child locations.

### What is the solution you are proposing?

Normally when clicking a location, you can see items for that specific location.  However the query for that location should also include it's child locations.  For bonus points, breaking these items down by sub-location (child locations) on this view with all children (and childrens children,  etc...).

Assuming you can easily query the names of the sub children, you could append these as an "AND WHERE location = sub-child1 AND WHERE location - sub-child2"  ...etc...) Or have them as separate SQL queries, and have these return in multiple sections on this same parent location view to easily tell what's where.

### What alternatives have you considered?

Using the filter, you can add all the proper parent/children locations.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I'm wondering if this is still necessary given the improvements to the tree viewer since it now supports

- Nested Locations
- Nested Items

Seems like that would be the primary way to navigate?
