### ISSUE TITLE
Optional field to automatically add tags to items in specified location

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#239]
### What is the problem you are trying to solve with this feature?

The ability/option to automatically apply a specific tag when creating new items on a location.  For example:
Home  ▶ Storage Unit  ▶ Toolbox

If I have a "tools" tag, I might want to auto-apply the tools tag on new items in the Toolbox location.  In my use case, 70% of the things in my toolbox are tools (Others are spare parts, specific types of screws, etc...).  But generally automatically having these tags selected when creating the new item would be helpful

### What is the solution you are proposing?

On the "location" edit page, add a new entry area called "Auto Tags" (that looks and functions identically as the normal tags window).  If a tag(s) are selected, when creating a new item under that location, these tags are automatically selected on the create new item screen.

### What alternatives have you considered?

Manually adding tags.  However I feel like I would rather have some items that dont need the tag and show up in a tag search, then to be checking inventory for a specific tag and have items missing.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't think this would be a widely used feature. I'll keep the issue around for a while to see if there's some additional interest, if not I'll close it out as won't implement

If you'd like to see this issue leave a 👍 reaction to the original issue.

**Comment by icsy7867** [comment]
> I don't think this would be a widely used feature. I'll keep the issue around for a while to see if there's some additional interest, if not I'll close it out as won't implement
> 
> If you'd like to see this issue leave a 👍 reaction to the original issue.

Fair enough.  Was an idea, but I just appreciate you guys listening!
