### ISSUE TITLE
Support nested locations with import 

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#256]
### What is the problem you are trying to solve with this feature?

I just tested importing about 300 items from a tsv.  Worked great except for some gotchas.

But since I did not see a way to support nested locations, I thought I would suggest it.  I had to append all the names with locations identifiers (For my storage unit and dual shelves, L3 would be left shelf, third shelf) 

But it would be great to have some support for this.

### What is the solution you are proposing?

I was trying to logic my way through this and it is a hard problem to solve.  It appears you can have multiple locations of the same name (which is a good thing I think).  But being able to does nesting is difficult.  A single child location is easy, but since you can have multiple it's a harder problem.

You could either, if the location exists, have a location ID, Or support a path of sorts.

If the location field supported, for example,
Root / child / child 2
This could work (although the slashes might not work in csv/tsv files)

I would remove any spacing before or after the slash(because humans are awful at consistency), and then make that into an array.  And then for each location/sub location, they would automatically create (or use existing locations if it exists with that parent)

### What alternatives have you considered?

It's a hard problem to solve when you are identifying locations by name and you can have multiple things matching the same name.  My strategy was to append the item names with locations/sub locations so after the import I would know where to attach it too.  My case my be unique, but I have a lot of sub locations 
Storage -> left shelf -> row 5 -> left box -> bag -> item (for example)

### Additional context

Loving what you are doing with the app and sorry for submitting so many ideas/features!  If it doesn't fit your plan feel free to reject.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
See #261 for newly proposed format + some other changes to the import
