### ISSUE TITLE
Show full path of a specific item.

### ISSUE THREAD

**Issue by icsy7867** [hay-kot/homebox#257]
### What is the problem you are trying to solve with this feature?

If I am trying to find a specific item, and I find it, it would be nice to show the entire location (Including all parent/children)

If I search for an item, and it's location is "Plastic Bin", I would probably want to know that it is "Basement -> Closet -> Plastic Bin" (as an example)

### What is the solution you are proposing?

I could see two approaches.

Either changing the label/tag under the name to incldue the entire path.  

Or if you want to keep that clean, you could include it under the "Details" section.  For my specific case, if I am searching for an item, it's full location is probably the next thing I want to know.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by alex-vision** [comment]
I agree, this would be extremely helpful when you have items nested deep. Would love to see this added, I’d be willing to sponsor some development time for it.

**Comment by RandomLegend** [comment]
+1 from me aswell! This is what i need.

I made children called Drawer 1, Drawer 2 for example for my shelf and put things in there. When i find something it just shows Drawer 2, but doesn't show me the parent because i have multiple Drawer 2's in multiple shelfs

**Comment by RandomLegend** [comment]
@hay-kot 

is there a setting to enable this? Because i updated my docker-compose and i still don't see the full path.

**Comment by hay-kot** [comment]
It was just merged, you'd either have to use the nightly tag or wait for the next release.

**Comment by RandomLegend** [comment]
Sorry, i thought i was on nightly - my bad.

Thank you and have a nice day
