### ISSUE TITLE
Adding a new user to an existing group recreates/duplicates locations and labels

### ISSUE THREAD

**Issue by proffalken** [hay-kot/homebox#258]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

nightly

### What is the issue you are experiencing?

I configured a new instance of Homebox for our Makerspace, deleted all the default locations as they weren't appropriate and then added a couple of new locations that we needed.

I then sent the invitation link to some other members of the space, however when they logged in the platform recreated all the locations that I had deleted and duplicated the default labels that were already in the system.

### How can the maintainer reproduce the issue?

1. Create a fresh installation of Homebox
2. Register and log in
3. Delete the default locations and add some custom ones
4. Use the "invite to group" link to create a new account in a different browser session
5. Sign in using the new account
6. Note that the deleted locations have been recreated and the default labels have been duplicated.

### Deployment

Docker (Linux)

### Deployment Details

System otherwise deploys and works as expected.

**Comment by hay-kot** [comment]
Yikes. That's super annoying. Looks like an easy fix would be to put these behind a guard clause

https://github.com/hay-kot/homebox/blob/7b28973c60a23c6f5f6878e89a262680361454d4/backend/internal/core/services/service_user.go#L92-L104

Will fix it later this weekend if no one else get's around to it
