### ISSUE TITLE
Add option to import database from Magic Home Inventory

### ISSUE THREAD

**Issue by jose1711** [hay-kot/homebox#280]
### What is the problem you are trying to solve with this feature?

So far I've been using Magic Home Inventory (https://play.google.com/store/apps/details?id=net.twisterrob.inventory&gl=US) to keep track of my items. It would be great if homebox includes an option to import the data and I would not have to invent my own solution.

### What is the solution you are proposing?

Magic Home Inventory supports export to a ZIP file with an easy to read structure. A converter should be able to read the items and convert them to fields homebox understands.

### What alternatives have you considered?

A custom (one-time) python script would probably do the job.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! I won't be adding imports from other services, we do have an API and a CSV importer, hopefully between the two of those someone could work something up for this.
