### ISSUE TITLE
show item without having to log in via QR code

### ISSUE THREAD

**Issue by Festeazy** [hay-kot/homebox#281]
### What is the problem you are trying to solve with this feature?

an option to allow a item to be public facing with a direct link. 

for some items, id like the QR to show the item description without having to log in. so if my family, friends scan the device they can get details without needing to create a login. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by tekjoey** [comment]
I think requiring a login defeats the whole purpose of having a QR code. Just my two cents, but I 1,000% want this.

**Comment by hay-kot** [comment]
I think it would make more sense to implement a longer login token option so users would be able to login-less, if that's the concern. 

Given how ingrained the identity is of a user to everything and that this would effectively expose all Item information for all users publicly, I have no plans to make this change.
