### ISSUE TITLE
ZPL/EPL support

### ISSUE THREAD

**Issue by gorbak25** [hay-kot/homebox#283]
### What is the problem you are trying to solve with this feature?

I want to use my zebra label printer with this software. Currently I'm managing my inventory using a spreadsheet and manually printed labels.

### What is the solution you are proposing?

For homebox to integrate directly with Zebra printers and to support other code formats than QR.

### What alternatives have you considered?

Manually generating labels in a windows VM with ZebraDesigner.

### Additional context

I'm looking for something to manage my inventory which is better than my spread sheets.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
> For homebox to integrate directly with Zebra printers and to support other code formats than QR.

I don't have a Zebra Printer. Can you provide any details on what sort of format your expecting here?

**Comment by BR-Nicholas-Prado** [comment]
ZPL is [Zebra's answer](https://www.zebra.com/content/dam/zebra_new_ia/en-us/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf) to postscript for defining what to print. It looks like there is a [go library](https://github.com/SimonWaldherr/zplgfa) for zpl. I steered the company I work for toward printing a pdf instead, given that we already used a reporting framework and didn't want to reverse engineer arbitrary pdfs into ZPL equivalents

```
// prints a simple image by sending binary value
String command =  "^XA\n^FO100,100\n^GFB,70,70,7,1111111010110101011010101101010110101011010101101010110101011011111111\n^XZ";
```

**Comment by dtimes** [comment]
not sure if printing binary via ZPL is really a good idea, this hugely increases  print job size compared to plain ZPL. Creating a label template in zebra designer is quite easy + the integration in the software should be easy ( if it´s a network connected printer it´s basically just piping the cleartext zpl to the printer´s port). I can look into creating a template if someone attaches the wanted layout to the issue

**Comment by hay-kot** [comment]
I won't be implementing this in application. Though, we do have an API - you can track this issue for updates on making using the API easier

- https://github.com/hay-kot/homebox/issues/314
