### ISSUE TITLE
[deployment] Helm chart

### ISSUE THREAD

**Issue by nicolas2bonfils** [hay-kot/homebox#318]
### What is the problem you are trying to solve with this feature?

As a Kubernetes user, I would like to have an helm chart to deploy easily on my cluster

### What is the solution you are proposing?

I made an [helm chart](https://github.com/nicolas2bonfils/helm-homebox). All suggestions/bug report are welcome.

### What alternatives have you considered?

use directly docker but but cluster would be useless :(

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! I don't have any experience of use for Kubernetes. Moreover I think properly supporting Kubernetes would require us to switch to a non-sqlite database and that isn't an option for the project right now.

Hopefully the community helm chart is enough to keep it going. Thanks!

**Comment by chevdor** [comment]
I am using Homebox in k8s using sqlite. Many say it can be an issue but:
- I am using a proper NFS (v4) version
- I let k8s do frequent backups

It is fast and simple, that makes it a very nice solution.

Supporting k8s is more about having a good Docker image than anything else.

Having a helm chart is nice but homelabs are all so different that the usefulness is limited IMO but that remains good to have. 

My take on that is that goodwill k8s support is:
- a good docker image (ie rootless, config file support and ENV). The current one is not rootless but the rest is pretty good already
- a set of manifest in the doc to get a basic homebox rolling in k8s

The later in my case looks like:
- 01_namespace.yml       
- 02_storage.yml          
- 03_deploy.yaml          
- 04_service.yaml         
- 05_ingress.yaml         
- OPT: 06_networkpolicy.yaml 
- OPT: 10_backup.yaml
