### ISSUE TITLE
Add the possibility to show image in the details tab and/or in location 

### ISSUE THREAD

**Issue by krloshenao** [hay-kot/homebox#319]
### What is the problem you are trying to solve with this feature?

Love this software it's simple and is easy to understand to not technical people, in my use case I'm working with a lot of electronics, cables, PCBs once per week one person come to my home and help me with the cleaning, I would like to show her the details page in one step, and not opening the attachment in another tab, 

### What is the solution you are proposing?

A check box show image in detail page 

### What alternatives have you considered?

If the attachment is an image fire it Will show automatically in the details tab

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by stegl** [comment]
This already exists? but you have to select the type of attachment to image?  
![Untitled-homebox](https://user-images.githubusercontent.com/65857447/221692420-135822fd-c242-4259-88f8-591c03d82ddb.png)

**Comment by hay-kot** [comment]
Closing since it looks like this is already implemented
