### ISSUE TITLE
Inbox / Input queue prefilled with purchases from Amazon

### ISSUE THREAD

**Issue by jk** [hay-kot/homebox#338]
### What is the problem you are trying to solve with this feature?

Reduce the back and forth between browser tabs to import my Amazon purchases into Homebox

### What is the solution you are proposing?

A generic inbox / input queue view where items can live until they're properly enriched with metadata and location. Mostly, items without a location can should appear. Like Todos following the »Getting Things Done« mythology which aren't moved into a project.

Since most of the stuff I buy, is bought from Amazon, it would be handy if homebox can query Amazons API periodically to find new purchases to prefill the inbox / input queue.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I've also though about this a bit. They do have a CSV export which I'd be more inclined to support, but I just looked at it looks like they're removing support this month :(

I don't think I want to include 3rd party related services like this in the core - It adds a lot of overhead for maintaining the application long-term. IMO This is something that should be done via the API and/or a side-car container that could interact with the API.

Currently the API isn't well documented, I did/am-doing a bunch of cleanup in #337 for the API endpoints and add a docs link so you can actually view the API docs and you can't really generate API tokens without manually logging in or getting a token from browser cookies so it's difficult to use at the moment. It will improve in the next couple of versions though. 

Once 

- #314 
- #337 

Are both closed it should be a lot easier to work with the API.

**Comment by hay-kot** [comment]
I won't be implementing this in application. Though, we do have an API - you can track this issue for updates on making using the API easier

- https://github.com/hay-kot/homebox/issues/314
