### ISSUE TITLE
Add markdown support to the log entries

### ISSUE THREAD

**Issue by chevdor** [hay-kot/homebox#349]
### What is the problem you are trying to solve with this feature?

There is a very limited amount of fields for the log entries and this is fine as it is.
I would be however useful to support external links to add links to an invoice, a product, etc...

### What is the solution you are proposing?

Add markdown support so that `[link](http://example.com)` is rendered as an hyperlink

### What alternatives have you considered?

Not many **simple** alternatives I fear

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
It should, have you tried it? This is from nightly, but the code looks like it's in the latest version as well

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/64056131/225382001-86ba5118-6227-4350-b55d-2466530a30ab.png">

**Comment by chevdor** [comment]
Oh I understand my confusion... It is only a Theming issue.
The link does not **look* like a link, it has the same font than the rest. But the is indeed a link.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/738724/225565994-a11bccfa-8334-486d-aa26-80b63f64e7e4.png">

Thanks for responding so quick @hay-kot
