### ISSUE TITLE
Rephrase tagline to appease the masses

### ISSUE THREAD

**Issue by pyramidofgreatness** [hay-kot/homebox#367]
### What is the problem you are trying to solve with this feature?

Ok, this is sort of a pedantic request.. but I've set up HB instances for several senior citizens, who are annoyed or offended by the tagline "Track, Organize, and Manage your Shit."

Kudos because the interface is generally simple enough for them to use

### What is the solution you are proposing?

Rephrase to:  "Track, Organize, and Manage your Stuff."

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Lmao. I can't believe it took this long. I will change it in the next release 😆
