### ISSUE TITLE
Ability to export data in the same format as required for importation of data

### ISSUE THREAD

**Issue by MartynWilliams** [hay-kot/homebox#370]
### What is the problem you are trying to solve with this feature?

The ability to make large scale changes to inventory locations (Boxes denoted as assets) without have to change individual assets via the GUI.

### What is the solution you are proposing?

Export the data in the DB, make modifications to locations as required, import data back to the database. Updated records now show the updated location.

### What alternatives have you considered?

None - this is the simplest solution I can think of at present.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This is already implemented in nightly, check it out in the demo site.

https://homebox.fly.dev/tools

Will be in the next release dropping in about a week or so.

**Comment by MartynWilliams** [comment]
Hey ! that's wonderful.... I only started playing with this today and it's great. 
My use case (for now) is to track consumables in storage bins, so my aim at the moment is the get the storage bins classed as assets (with an ID)  and add contents (without ID) as I go.

I'll be working up to adding tags to all of my assets as time permits.

Once again thanks for the update.
