### ISSUE TITLE
Hierarchic labels

### ISSUE THREAD

**Issue by chevdor** [hay-kot/homebox#394]
### What is the problem you are trying to solve with this feature?

Currently labels are independant.
Consider however an item such as a Touch TFT Display.
It would be interesting to be able to nest Labels such as:

Display > TFT Display > Touch TFT Display

Then, similar to https://github.com/hay-kot/homebox/issues/321 we could search the item using its label and find a hit as long as the searched labels belongs to the parent tree.

For instance, this `Touch TFT Display` labelled `Touch TFT Display` should show up when searching for:
- Touch TFT Display
- or TFT Display
- or Display

### What is the solution you are proposing?

This probably requires a rework of the Label model to support an optional parent, as it was done for the locations.

### What alternatives have you considered?

I consdered using multiple labels but the current UX makes it a pain to quickly select multiple labels.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
> I consdered using multiple labels but the current UX makes it a pain to quickly select multiple labels.


I don't understand this problem, can't you just open the dialog and click the labels you want? Given that Locations and Items are both nested, I'm not sure why we'd need to make labels nested as well. 

> Display > TFT Display > Touch TFT Display

I have a hard time imagining that people would implement this kind of granularity. It's an interesting idea but would require a lot of overhead to add all these tag nestings. 

If anyone else would use this feature, please react to the original issue or let me know.

**Comment by chevdor** [comment]
The first issue is that scrolling through the list of labels is far from being the quickest option and the best UX.

The benefit of nested labels is that you get some automatic labelling and don't have to bloat the list of labels with the parent labels. Scrolling being a pain today, this is part of the issue.

The labels in [this project](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/demo/) (just an example) are handled in a more practical way:
- first there is no need to create the labels, just set one and it will be created, the auto-completion helps avoiding similar duplicates
- this meets another bug related to newly created labels NOT available unless you force refresh the UI
- autocompletion of the labels is much quicker than scrolling through a list as soon as you get a decent amount of labels

I guess I should have split this issue into 2:
- better UX for the labels as they exist today (auto complete from a text field, auto creation)
- Hierarchic labels

The second becomes less of a necessity if the first works very well.

**Comment by hay-kot** [comment]
> better UX for the labels as they exist today (auto complete from a text field, auto creation)

I think this is totally reasonable. It's a lower priority because I think if you're running into this being a problem, it would likely make more sense to use the import/export feature for bulk updating the items

Happy to accept a PR or sponsored work, but not something I'd be looking into anytime soon.
