### ISSUE TITLE
Add Thai baht (THB) Currency

### ISSUE THREAD

**Issue by kangver** [hay-kot/homebox#408]
### What is the problem you are trying to solve with this feature?

Your Project is Great I love it. Can you please add Thai Baht (THB) in the currency list.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hitokirihahn** [comment]
Please add more currency for example Indonesia Rupiah (Rp).
