### ISSUE TITLE
Make some items act as locations by adding checkbox to create item screen.

### ISSUE THREAD

**Issue by drewjprosser** [hay-kot/homebox#410]
### What is the problem you are trying to solve with this feature?

Often I find that I am putting items inside things I would also like to consider as items, but have to make locations to make the hierarchy make sense. For instance, my Processor lives in my Chassis, which are both items. However the Location for my Processor is my Living Room. 

Flow right now:
(Location) Apartment -> Living Room -> Chassis, Processor
(Items) Apartment -> Living Room -> Chassis -> Processor

So the Location Hierarchy makes sense, but when I open my Living Room location, it shows all of my computer parts in addition to all other items in that Location. I would prefer that it shows just the Chassis item, with the parts all under that item.

I have used the Parent Item feature, but it still selects and displays under the Parent Location, whereas I would prefer to have the click path Go Location -> Location -> Item as Location -> Item if it is a part of something.

Flow I'm proposing:
(Location) Apartment -> Living Room -> Chassis ->Processor
(Item) Apartment -> Living Room -> Chassis -> Processor

When searching as well, If I want to see all the items in my Living Room, I would want to see the Chassis item, but not the Processor item.

### What is the solution you are proposing?

A checkbox that says something like "also use item as location" on the create item/asset popup. This would make an item also act as a location, storing other items.  This might invalidate the need for the "Parent Item" Attribute, but still could be used for legacy and just duplicated on new items e.g. Parent Location "Item X", Parent Item "Item X".

### What alternatives have you considered?

Using the Parent Item attribute. This works for the Location Hierarchy page, but not for the individual location pages.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by drewjprosser** [comment]
Just thought of this, could just make it so items with Parent Item attribute do not show up under Parent Location page. This solves most issues other than my Processor saying it's located in the Living Room instead of my Computer.

**Comment by intuadmin** [comment]
suggested solution to have items that follow the location of the parent object https://github.com/hay-kot/homebox/issues/429#issuecomment-1518533248 would also work here

**Comment by PreHack1** [comment]
I think something like this could be a great improvement, but I would like to be able to make an item a location not only when the item is created, but also later. An option on the Edit Item page to make an item also a location would be great. That way I could just use it like any other location.
I would also consider unifying items and locations, so maybe every location is an item.

**Comment by hay-kot** [comment]
@PreHack1 

> I think something like this could be a great improvement, but I would like to be able to make an item a location not only when the item is created, but also later. An option on the Edit Item page to make an item also a location would be great. That way I could just use it like any other location.

Can you speak more specifically to what behavior you'd expect to change that's different from what's currently possible with nested locations/items?

@drewjprosser Would it be sufficient to provide a more granular filter to the locations children? Like having a toggle for `only show direct children` vs `show all children` when on the location page?

**Comment by mxafi** [comment]
Very cool idea! Here's my two cents:

- An intuitive user "flow" would be that items could be marked as containers, then when viewing that item, there would be a section showing the items that are inside of it.
- The new item button would automatically set the location for the new item to be the container item when clicked in this view.
- When viewing a location, only items that are not inside of container items would be shown.
- When moving a container item from location A to location B, the items inside of the container should move location with it. (this enables labeling moving boxes and making a move from an apartment to another way easier)

Don't know how viable any of this is with the current database setup but hopefully this comments gives some inspiration.

**Comment by hay-kot** [comment]
Tracking this work in #696

**Comment by ngirard** [comment]
Wow ! Thank you very much @hay-kot !
