### ISSUE TITLE
Manage digital assets (subscriptions, Insurances)

### ISSUE THREAD

**Issue by crashdown79** [hay-kot/homebox#412]
Being able to manage also digital assets like subscriptions or insurances or contracts.
Needs e.g. a date of month or yearly refresh date field
Needs e.g. a minimum term date

**Comment by hay-kot** [comment]
Please re-submit using the appropriate template.

![CleanShot 2023-04-13 at 14 16 08@2x](https://user-images.githubusercontent.com/64056131/231895224-e301324a-250f-4542-b2ab-2571987b815d.png)
