### ISSUE TITLE
Expose BasePath as env variable

### ISSUE THREAD

**Issue by bodak** [hay-kot/homebox#416]
### What is the problem you are trying to solve with this feature?

Serve homebox under a subpath on domain i.e.
https://homebox.fly.dev/ vs https://fly.dev/homebox

### What is the solution you are proposing?

New environment variable `HBOX_WEB_BASE` defaults to `/`.
Not familiar with the code base, so this might need to sit in https://github.com/hay-kot/httpkit

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't believe this is possible because Vue.js needs to know the base path at build time, not runtime, so you'd need to compile your own binary to get this to work. At least that was the case last time I looked into any of this for Mealie

**Comment by bodak** [comment]
@hay-kot Thanks for the reply.
I have very little understanding of Vue.js (or Go), but it might look like Vue/Nuxt supports this setting during runtime. However since the front-end is compiled with the backend, there is no access to this property I assume.
> In Nuxt 2.15+, changing the value of this property at runtime will override the configuration of an app that has already been built.
https://nuxtjs.org/docs/configuration-glossary/configuration-router#base.

A few questions on configurations:
- This config seems to be for backend tests, but there is a BaseURL parameter that is being set https://github.com/hay-kot/homebox/blob/bd321af29fb9f6c0c7d7d10cd049740be757ff5a/frontend/test/setup.ts#L9. Is this something that can contain subPaths and could be exposed?
- The Dockerfile references a `config.yml` that is passed as an argument, but haven't found what this looks like or what config it sets. https://github.com/hay-kot/homebox/blob/bd321af29fb9f6c0c7d7d10cd049740be757ff5a/Dockerfile#L50

**Comment by hay-kot** [comment]
> In Nuxt 2.15+, changing the value of this property at runtime will override the configuration of an app that has already been built.
https://nuxtjs.org/docs/configuration-glossary/configuration-router#base.

This is Nuxt 2, we use Nuxt 3. https://nuxt.com/

Either way, Nuxt is both a Server Side and SPA framework. Since we're using the SPA version, I don't believe it's possible to set a base url when there is no Nuxt server in deployment.

> This config seems to be for backend tests, but there is a BaseURL parameter that is being set

This is for the frontend to make API requests to the backend, we only set this during testing because we can't use a relative URL because the tests actually run in Node and not in browser. The issue likely won't be the API calls, that's easy to work around. It's how Vue handles routing that is a problem. 

> The Dockerfile references a config.yml that is passed as an argument, but haven't found what this looks like or what config it sets.

That's a relic from a much earlier version. It's not used anymore.

**Comment by clustor** [comment]
@hay-kot  Can you share the changes that need to be for building to specify base path?   I added the following to `nuxt.config.ts` but that doesn't seem to have any effect. 

```
  router: {
    base: '/homebox'
  },
```
