### ISSUE TITLE
Add 'Create and Add Another' option for locations

### ISSUE THREAD

**Issue by cauchy-schwartz** [hay-kot/homebox#423]
I like making a separate location for every shelf in my cabinets, etc. Creating this many locations takes time, but would be sped up a bit if the 'Create and Add Another' option for items also existed for locations.

**Comment by hay-kot** [comment]
FYI #526 adds support for this + additional keyboard shortcuts to do this for shift+enter so you can quickly add a bunch of items/labels/locations. 

![CleanShot 2023-07-31 at 12 34 16@2x](https://github.com/hay-kot/homebox/assets/64056131/6f5aaefd-e1ef-41a7-87d5-947ea374e311)
