### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by cauchy-schwartz** [hay-kot/homebox#424]
### What is the problem you are trying to solve with this feature?

Adding hundreds of items and locations takes a long time.

### What is the solution you are proposing?

Add keyboard shortcuts for common tasks, especially saving an item and continuing to the next (while keeping the parent location of the item/location just saved and keeping focus in the field active when the keyboard shortcut is used, e.g. item name).

### What alternatives have you considered?

Direct database and .csv editing seems possible for mass entry, but is unwieldy.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
It would be great to have a more keyboard accessible interface, I'd love to have some kind of command pallette for common tasks.


> Adding hundreds of items and locations takes a long time.
> ...
> .csv editing seems possible for mass entry, but is unwieldy.

Can you expand on why the CSV is unwieldy? It exists specifically for this purpose.

**Comment by cauchy-schwartz** [comment]
> It would be great to have a more keyboard accessible interface, I'd love to have some kind of command pallet for common tasks.
> 
> > Adding hundreds of items and locations takes a long time.
> > ...
> > .csv editing seems possible for mass entry, but is unwieldy.
> 
> Can you expand on why the CSV is unwieldy? It exists specifically for this purpose.

Perhaps I haven't really given it a fair chance with the .csv, as it's not something I'm used to working with. But there are a few things which I do think make it somewhat unwieldy:

1. As far as I can see, it doesn't work for locations. Only items can be added in a .csv.
2. It is not immediately possible to search for locations. You have to type the entire path - and since I like to nest my locations 6 or more levels deep, down to each individual shelf and compartment at least, this gets quite long.
3. There are a lot of fields in the .csv that I'm normally not interested in setting (especially things like ID's and insured status, but in most cases, everything but parent location (and sometimes parent item), name and sometimes description. The fields aren't really ordered in the order I at least use them most.

**Comment by hay-kot** [comment]
I'd take another look at the docs for the latest version, I rewrote the CSV format and importer in v0.9 and it's pretty powerful/flexible now. 

https://hay-kot.github.io/homebox/import-csv/

Mainly

1. Any Tags or Locations you use will automatically be created
2. Supports nested locations via `Root / Child 1 / Child 2` Syntax
3. Pretty much all fields are no option with the new format. I think you only need a location and a name field. 
4. Supports Custom Fields
5. Supports updating existing items (via Import Ref match)

**Comment by PreHack1** [comment]
The CSV import, is a wonder weapon but it's also somewhat wrong to use it for more then a temporary solution if a user interface inprovment would remove the need for it. I love Homebox because I don't need to stare at a Table :)

I would love to see shortcuts added.

**Comment by hay-kot** [comment]
Do you have an example of the keyboard shortcuts that you'd be looking for? I find that most web apps that take over keyboard shortcuts get in the way more than anything else so I'm hesitant to add them. Do you have an example of a website that has a good implementation of this?

**Comment by moritzruth** [comment]
Being able to close a modal dialog by pressing <kbd>ESC</kbd> would be great.

**Comment by hay-kot** [comment]
> Being able to close a modal dialog by pressing Escape would be great.

Addressed in 

- https://github.com/hay-kot/homebox/pull/526

---

Also if anyone in this thread wants to propose a list of keyboard shortcuts and what they would do I will add it to the roadmap.
