### ISSUE TITLE
All items gallery view - see thumbnail for each item when an image was attached (Similar to Windows View -> Medium icons)

### ISSUE THREAD

**Issue by pytlv** [hay-kot/homebox#425]
### What is the problem you are trying to solve with this feature?

Hello and thank you all.
Currently I'm managing my home inventory in Airtable.
In the default view, I have an image of the item (see attachment).
 
![2023-04-17 11_18_02-Home Inventory 2022_ Items - Airtable](https://user-images.githubusercontent.com/37730957/232426609-dbdd565e-9dbd-4b78-934a-0ea7b0ccff88.jpg)

### What is the solution you are proposing?

Thumbnail \ Gallery View

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by PreHack1** [comment]
I like it, but isn't this already on the roadmap? or what's the difference to your request?

[Display Primary Image on Items Pages](https://github.com/hay-kot/homebox/issues/33)

**Comment by pytlv** [comment]
Thanks, I was not aware of the roadmap and could not find existing issues with that request.
Maybe good idea to add "thumbnails" or "gallery" to the line item in the roadmap.
Many thanhks!

**Comment by hay-kot** [comment]
Closing as duplicate (covered in roadmap) Thanks!
