### ISSUE TITLE
Attach receipts to individual maintenance items

### ISSUE THREAD

**Issue by es9o** [hay-kot/homebox#428]
### What is the problem you are trying to solve with this feature?

I've started using Homebox to track maintenance history for some of my appliances and would love the ability to attach receipts to individual maintenance items rather than attaching them to the item itself.

### What is the solution you are proposing?

Add the ability to add receipts to maintenance items to prevent clutter amongst the actual item uploads.

### What alternatives have you considered?

I'm currently uploading all maintenance receipts to the item, which is creating clutter.

### Additional context

N/A

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This is planned see 

- https://github.com/hay-kot/homebox/issues/14

Closing as duplicate
