### ISSUE TITLE
Remove locations, make items and locations equal.

### ISSUE THREAD

**Issue by PreHack1** [hay-kot/homebox#429]
### What is the problem you are trying to solve with this feature?

I have my bookshelves as an item and I have my books as an item. Each book has the bookshelf it is in as a parent item. Now, if I want to move a book from the shelf in my living room to the shelf in my bedroom, I need to change the parent item and the location of the book.

### What is the solution you are proposing?

Having parent items and locations is not the right approach, in my opinion. There should be no locations and only items, every location could just be an item.

### What alternatives have you considered?

I may use it wrong and don't understand the advanteges of this aproach.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by intuadmin** [comment]
Nesting items is expressing an arbitrary relation between them that can be something different than the location. As an example multiple items kept at different locations can be related to the same parent item that might be a contract covering these items.

To solve this problem I would suggest to provide an flag to enable/disable the synchronization of an items location together with the parent. This allows to have items that can have a location independent from their parent item as well as items that get moved into a new location together with their parent.

**Comment by hay-kot** [comment]
> I have my bookshelves as an item and I have my books as an item. Each book has the bookshelf it is in as a parent item. Now, if I want to move a book from the shelf in my living room to the shelf in my bedroom, I need to change the parent item and the location of the book.

Seems like this would go

Bookshelf (Location) -> Shelf 1 (Location) -> Book 1 (Item)

--

I don't really understand why you would want what your asking other than personal preference. Using stricter Location/Item definitions is a better mental model IMO. I don't really see a strong use case for Item -> Item nesting except in rare cases.

**Comment by PreHack1** [comment]
I now see how the parent element can be used for relationships between elements other than location. I want to use my shelf as a location, which seems like a simple solution, but I also want to have my shelf as an item and it feels wrong to enter it twice.

I think https://github.com/hay-kot/homebox/issues/410 would be a great solution for what I want.

**Comment by hay-kot** [comment]
> but I also want to have my shelf as an item and it feels wrong to enter it twice.

Why do you want it as both?

**Comment by PreHack1** [comment]
Because it is an item, something of value that I think I should have in my inventory. It's also a location, I think it helps me find my stuff faster if it's on the right shelf instead of just in the room.

A better example would be maybe the boxes that I have, I have a lot of little things in boxes, I put a qr code on the boxes so I can get an inventory of what is in them. These boxes are items because I have 40 of them and each one costs $15. Right now, the box is the parent item, even though that is probably not the right use for it because there is absolutely no relationship between the box and the items in it except for location. So if I move something from one box to another, the parent item changes and sometimes the location changes as well.

Maybe I'm wrong about how I want to use this, but I also don't see the argument for having locations and items when locations could just be items. I may need to change my thinking about this, but I just feel like this project isn't v1 yet, so if something like this needs to be rethought then now is going to be the time later it will be very cumbersome.
