### ISSUE TITLE
Provide options to format/remove the "-" in the Asset ID Field

### ISSUE THREAD

**Issue by michaelruge** [hay-kot/homebox#439]
### What is the problem you are trying to solve with this feature?

The asset id has a "-" in the middle of it. I already have pre-printed asset tags and this makes it hard to use those tags. I have to create a custom field for each item that has the actual asset id without the "-" in it.

### What is the solution you are proposing?

Either add the ability to  remove the dash or allow for format options to the Asset ID.

### What alternatives have you considered?

Creating a custom field for each item with the asset id that is on my preprinted tags.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by adamantike** [comment]
This seems to be just a frontend change. The `asset_id` field is an integer in the database, but the frontend has the formatting logic to add a dash after the first three digits: https://github.com/adamantike/homebox/blob/c1957bb9278132182bb7ddb7a838523032d96d9c/frontend/pages/reports/label-generator.vue#L161-L167
