### ISSUE TITLE
Can't add more items

### ISSUE THREAD

**Issue by fcarucci** [hay-kot/homebox#441]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

latest

### What is the issue you are experiencing?

Hello, thanks for the great work. When I try to add an item, I get this error in the log.

5:40PM INF ../go/src/app/internal/web/mid/logger.go:25 > request received method=POST path=/api/v1/items rid=e4b4decc0b98/nOFOWbG0pc-000033
5:40PM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="ent: constraint failed: constraint failed: FOREIGN KEY constraint failed (787)" req_id=e4b4decc0b98/nOFOWbG0pc-000033

I have only few items. Testing the app.

### How can the maintainer reproduce the issue?

- try add an item

### Deployment

Docker (Linux)

### Deployment Details

Docker swarm.

**Comment by hay-kot** [comment]
Do you have a location set in the creation dialog? It's a required field, the UI doesn't provide great feedback at the moment.
