### ISSUE TITLE
Initial Migration Files Missing in Binary Build

### ISSUE THREAD

**Issue by feamsr00** [hay-kot/homebox#445]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.9.1

### What is the issue you are experiencing?

when running
`>.\homebox.exe`

```
panic: open migrations\20220929052825_init.sql: file does not exist

goroutine 1 [running]:
main.main()
        /home/runner/work/homebox/homebox/backend/app/api/main.go:55 +0x72
```

### How can the maintainer reproduce the issue?

download [homebox_Windows_x86_64.zip](https://github.com/hay-kot/homebox/releases/download/v0.9.1/homebox_Windows_x86_64.zip) extract and run homebox.exe

### Deployment

Other

### Deployment Details

Windows 22H2 (10.0.19045.2846)

**Comment by hay-kot** [comment]
From Discord

> I've got a lead in relation to running homebox natively on windows. There a backslash-forwardslash issue when dealing with embeded paths (https://github.com/golang/go/issues/45230).
