### ISSUE TITLE
Create Attachment API Usage Error

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [hay-kot/homebox#446]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.9.1

### What is the issue you are experiencing?

Can't seem to use the create attachment item to upload an attachment.
Other api such as create item, update item, create location & create label work.
```
attachment_req_header = {"accept": "application/json","Authorization":token,"Content-Type":"multipart/form-data"}

with open(filepath, 'rb') as file:
  attachment1_data = {"type":"application/pdf","name":filename}
  files={'file': (filename, file, 'multipart/form-data')}
  response = requests.post(url=item_url+"/"+item_id+"/attachments", data=attachment1_data,headers=attachment_req_header, files=files)
```

Error - 
12:02PM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_items_attachments.go:39 > failed to parse multipart form error="no multipart boundary param in Content-Type"

12:02PM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="failed to parse multipart form" req_id=a48eeaa53a88/f8hLluEauu-002848

### How can the maintainer reproduce the issue?

Using the above code (python)

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
I think you're setting too many headers in your request?

https://stackoverflow.com/questions/17415084/multipart-data-post-using-python-requests-no-multipart-boundary-was-found

**Comment by Gandalf-the-Blue** [comment]
That was it! Removing the Content-Type in the header worked. Thank you :)
