### ISSUE TITLE
New items pull through details of last asset

### ISSUE THREAD

**Issue by katosdev** [hay-kot/homebox#452]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.9.1

### What is the issue you are experiencing?

When logging a new item on Homebox, the details are pulled through of the last asset that was logged.
Similarly, when creating a new label this is not available to new items until a hard refresh is completed - suggesting that this is an aggressive cache causing the issue.

### How can the maintainer reproduce the issue?

1. Create a new item
2. Fill in test description and notes
3. Edit item and amend further as required
4. Log a new item
5. Edit the second item and the description will be that of the first item. 

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
This should be fixed. Please verify with the latest version and re-open or create a new issue if it's still present. 

Thanks!
