### ISSUE TITLE
internationalization support

### ISSUE THREAD

**Issue by terion-name** [hay-kot/homebox#456]
### What is the problem you are trying to solve with this feature?

Hello! Neat project =)
Looked a bit and thought about internationalization support. It's kinda important for such apps, not all home users in the world speak English) Maybe I even could participate in this update

On frontend part it's kinda easy, nuxt-i18n will handle this.

Will this be enough, or backend also generates predefined texts and also needs to be modified for i18n support? Didn't work with Go a lot so don't know how things are there about this

### What is the solution you are proposing?

On frontend part add https://nuxt.com/modules/i18n
On backend — ?

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Duplicate #152
