### ISSUE TITLE
Demo instance doesn't work, wrong password

### ISSUE THREAD

**Issue by C-Fu** [hay-kot/homebox#47]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

-

### What is the issue you are experiencing?

Demo site doesn't work, maybe somebody changed the password?

### How can the maintainer reproduce the issue?

Go to the demo site

### Deployment

Other

**Comment by CorneliousJD** [comment]
I saw the same issue, I just deployed a container to check it out instead, but having the demo instance working would be ideal.

**Comment by palanthas** [comment]
I was able to create a new account and play with that.
