### ISSUE TITLE
Setting to Remove "Register New User" button on Login Screen

### ISSUE THREAD

**Issue by gth758y** [hay-kot/homebox#476]
### What is the problem you are trying to solve with this feature?

After all users have been added, it would be nice to be able to remove the "Register New User" button on the login screen. I'd like to expose Homebox through my reverse proxy, but having the new user button means that anyone who stumbles onto the url could, in theory, create a new user. I'd like the ability to remove the new user button.

### What is the solution you are proposing?

A toggle either in settings or a command in Docker to remove the new user prompt

### What alternatives have you considered?

Not exposing Homebox through the reverse proxy and/or utilizing a VPN or similar for off-premises access

### Additional context

I believe Vault Warden has implemented this type of feature. I'd love to help implement and maintain the feature if it's accepted, but sadly I lack the skills to be useful.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This is already implemented 

https://hay-kot.github.io/homebox/quick-start/#env-variables-configuration

Specifically 

```
HBOX_OPTIONS_ALLOW_REGISTRATION=false
```

is what you're looking for.

**Comment by gth758y** [comment]
So it is- worked like a charm. Thank you!
