### ISSUE TITLE
Date not saved when typed in date fields

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#48]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.1.0

### What is the issue you are experiencing?

Dates are not saving when date is manually entered into date fields.

### How can the maintainer reproduce the issue?

1. Edit an item
2. Manually type the date in **Purchase Date**, **Warranty Expires** or **Sold At** instead of using the date selector _e.g. 01/01/2022_
3. Save your changes
4. Date is not saved

### Deployment

Docker (Windows)

**Comment by hunkyn** [comment]
Thanks i have the same issue as well for now selected through date selector

**Comment by PyroghostX** [comment]
same issue, happy to see its already reported. 
Along with it, if I click (many many times) to get to 1/26/2034, once i click that date, the date selector glitches back to 2022...
So I cannot get 2034 selected. 
1. It should accept manually typed in dates
2. It should have a year selector in the date selector thing. Lots of them have it, where you can click the year and it changes to year selector, then month, then day
Thank you Hay-kot! Loving homebox for storing my home purchases and warranty details

Want me to see if I can fix the date issues and do a pull request?

**Comment by hay-kot** [comment]
> Want me to see if I can fix the date issues and do a pull request?

Yes please! I would love to see some improvements in the date-picker. It is less than ideal right now.

**Comment by BCNelson** [comment]
@PyroghostX have you go a chance to work on this yet? If not I'm thinking about taking a look at it.

**Comment by PyroghostX** [comment]
@BCNelson I haven't had a chance yet, so it would be great if you take a look. I wont be able to until feb
