### ISSUE TITLE
Application allows HTML content for item description. 

### ISSUE THREAD

**Issue by autumnlewjb** [hay-kot/homebox#482]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.9.2

### What is the issue you are experiencing?

I added HTML snippets into the item description and save. It is expected to show an error that HTML content is not allowed. Yet, the item is saved, and it renders the HTML as it is on the DOM, making the user interface inconsistent. 

![Picture8](https://github.com/hay-kot/homebox/assets/49812781/5da6286b-dc19-43ba-b0de-60a44382ed77)

### How can the maintainer reproduce the issue?

1. Click “CREATE” button.  
2. Click “Item/Asset” option.  
3. Enter the value below to the respective fields.  
    Parent location = “Bathroom” 
    Item Name = “Bathtub” 
    Item Description = `<div style="background-color: yellow; height: 800px;"></div>` 
    Label = “Appliances, Electronics” 
4. Click “Create” button.  

### Deployment

Other

**Comment by hay-kot** [comment]
> It is expected to show an error that HTML content is not allowed.

Why is this expected? We support markdown, and HTML is supported within markdown.

I don't see the issue here.
