### ISSUE TITLE
Display photo attachments inside items list and search

### ISSUE THREAD

**Issue by WEZANGO** [hay-kot/homebox#488]
### What is the problem you are trying to solve with this feature?

This will help to identify the item quicker

### What is the solution you are proposing?

Make square preview of items inside the list item on left or right side

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by dominch** [comment]
this is obviously needed, for now attachments are hidden somewhere in details, this is good to organize some instructions and pdf for devices etc, but some gallery view with photo attachements would be awesome. For now I could not find anything there, just text.

**Comment by hay-kot** [comment]
FYI this is already on the roadmap. If you're interested in expediting the development process, It would really help to have a mock-up design of what it should look like. That's the biggest blocker for me right now.

Closing since we're already tracking here

https://github.com/hay-kot/homebox/issues/33

**Comment by dominch** [comment]
This should be rather intuitive, but let's try. Hopefully it's right place to put mockups: 

any grid view icon: 
![image](https://github.com/hay-kot/homebox/assets/10815109/d5d8ce6c-9f0c-4418-bd5d-d3f69ed6fdce)

detail view - top header image: 
![image](https://github.com/hay-kot/homebox/assets/10815109/414e98ed-d98f-4e64-a637-15fbb6d4b6c1)

detail view: attachments: 
![image](https://github.com/hay-kot/homebox/assets/10815109/eea14d6f-b49a-4515-a170-a3e7d27ef498)

**Comment by mztiq** [comment]
I'd love to see this too ...this missing feature is the only thing that makes me keep Snipe IT and I can't wait to see this implemented.

**Comment by dominch** [comment]
yes, let's try to help @hay-kot  with mockups and tests so he get's this idea :)
as far as I could use homebox for now it's very clever software with all needed options for home storage, but just lacks this one :)

**Comment by Doublemyst** [comment]
If this addition would be implemented, like in your mockups, this would be great!
