### ISSUE TITLE
Site data not refreshing correctly until page is manually refreshed

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#50]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.1.0

### What is the issue you are experiencing?

If an items location is changed, and then the user returns to the homepage, the count on the before and after storage location does not update until any storage location is opened, or the page is refreshed.

### How can the maintainer reproduce the issue?

1. Open the home page
![image](https://user-images.githubusercontent.com/4337361/195588433-de544732-af9c-43f5-9f0b-6e8292a705cf.png)

2. Select an item and edit its location
![image](https://user-images.githubusercontent.com/4337361/195589063-9a561ce7-a68f-4a54-968c-08949710ab60.png)
![image](https://user-images.githubusercontent.com/4337361/195589557-b21e9429-c47d-48db-8c8c-95a4219454e8.png)

3. Click on the HomeBox logo to return home, **storage location counts have not changed**
![image](https://user-images.githubusercontent.com/4337361/195589261-9279316c-00d3-4b99-818d-9a2706abb9da.png)

4. Refresh the page, or open any storage location and then click on the HomeBox logo to return home. Storage location counts are now updated.
![image](https://user-images.githubusercontent.com/4337361/195589492-baee5412-b61f-4c83-8b42-5cb3aa1a4045.png)

### Deployment

Docker (Windows)

**Comment by Motordom** [comment]
An update on this, there appears to be a system wide bug with data not refreshing on page change.

For example:

1. If you log out of an account (A), and login to a different account (B), the counts for locations/items/labels on the homepage will display those of account A, and the locations and labels on the homepage will be for account A until the page is refreshed manually
2. If you create a new user, login, go to profile and click delete, the popup will not appear until you manually refresh the page

**Comment by InsaneSplash** [comment]
I'm seeing the same here. To refresh the page of items or locations I need to refresh the page...

**Comment by hay-kot** [comment]
@Insprill I'm aware what is causing the issue, it's just going to be require a large refactor of the API client and I've been busy with a move, so it will be some time before I can fix the issue. A hard refresh of the browser _should_ update the values to the correct ones.

For anyone who wants to take a look at the code related to this issue. We need to change the API client to support a "proxy" wrapper and implement an observer pattern that can trigger an update whenever a CRUD action is done for the relevant API methods. Alternatively, we could use a web-socket connection and trigger the events from the server side, but we don't have any existing web-socket code so I'm not sure how much work is involved there.
