### ISSUE TITLE
Add an option for removing password strength requirements

### ISSUE THREAD

**Issue by tushev** [hay-kot/homebox#509]
### What is the problem you are trying to solve with this feature?

It's a good thing to prohibit use of weak passwords **by default**, and thank you for doing that! However, in some situations (airgapped networks, local Docker container w/o exposing to internet/intranet etc) these are unnecessary and annoying.

### What is the solution you are proposing?

Add env variable `HBOX_OPTIONS_DISABLE_PASSWORD_STRENGTH_CHECK`, false by default. When `true`, it omits all checks and allows setting `1` and `admin` as passwords

### What alternatives have you considered?

Require `HBOX_OPTIONS_DISABLE_PASSWORD_STRENGTH_CHECK` to contain string:`IKnowWhatImDoing` to become active :)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This isn't something I'm going to be adding into the application. 

Thanks for your request though!
