### ISSUE TITLE
Allow use of UNIX sockets instead of ports

### ISSUE THREAD

**Issue by tushev** [hay-kot/homebox#510]
### What is the problem you are trying to solve with this feature?

As of today, homebox supports only HTTP ports, amd does not support unix sockets.

### What is the solution you are proposing?

Add an env variable `HBOX_SOCKET_PATH`. When present, it overrides `HBOX_WEB_PORT` and HTTP server starts listening on the unix socket from specified path.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! I have no plans to do this work, I don't really know how too and am not interested in looking into it at this time. If you want, you can submit a PR to add this functionality. Thanks!
