### ISSUE TITLE
Wrong documentation for /v1/asset

### ISSUE THREAD

**Issue by AdamCarballo** [hay-kot/homebox#515]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.9.2

### What is the issue you are experiencing?

It seems the endpoint `/v1/asset ` is listed in all documentation I could find as `/v1/assets`, which ends up in 404.

The only way I managed to see the issue is by finding the exact route in the source code, where it was listed as `/v1/asset`. Maybe it was actually intended to be `assets` (plural) and the documentation is the one that's correct?

I would make a quick MR, but I'm not sure how the documentation is getting generated, if it comes from the file comments or somewhere else - and as I said, I'm not even sure what's the correct endpoint in the end.

### How can the maintainer reproduce the issue?

Try to get an asset using the API and the documentation by calling `/v1/assets/{id}`, get 404.

### Deployment

Unraid

**Comment by ressl** [comment]
The same issue is again in the version Version: v0.10.2 ~ Build: 8cc0f302919758044dc9ff4dc785c452364dc715
