### ISSUE TITLE
Unable to view the attachments forms when edit an item

### ISSUE THREAD

**Issue by sgiraz** [hay-kot/homebox#519]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.9.2

### What is the issue you are experiencing?

When I try to create or edit an new item / asset, a don't see the attachments form anymore.
I tried also with different browser and different user agents, but the problem persists wherever (also from mobile).

### How can the maintainer reproduce the issue?

You can try using the [demo app][1].

### Steps:
- login
- click on `create`
- fill the main form and click on `create`
- click on `edit`
- scroll down and see the missing attachments (photos, manuals, etc ...) form

![image](https://github.com/hay-kot/homebox/assets/18039045/a495b642-feed-4a8d-bafc-8cc31822a48a)

[1]: https://homebox.fly.dev/

### Deployment

Docker (Windows)

**Comment by hay-kot** [comment]
Have you enabled the Advanced toggle at the top of the edit page?

**Comment by sgiraz** [comment]
Hey @hay-kot, 

Thanks for the quick reply. 
I apologize for not checking it earlier, in fact it is still working.

I close this issue as not planned.
