### ISSUE TITLE
Add the option view attachments in browser

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#52]
### What is the problem you are trying to solve with this feature?

Currently to view an attachment, it must be downloaded and opened, it cannot be directly viewed.

### What is the solution you are proposing?

Add a view option for attachment to open the attachment as a popup, or view in a new browser window.

### Additional context

![image](https://user-images.githubusercontent.com/4337361/195592390-a6c7eaa1-c272-4139-9f1f-42e80c1ff41b.png)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by nobodyspecial** [comment]
I'll second this. Photos of items should appear on the items page.

**Comment by hay-kot** [comment]
- #166

Should allow for both the original request and what @nobodyspecial is asking for. Items will now have an image gallery for photo-type attachments.
