### ISSUE TITLE
Increase Password Max Length

### ISSUE THREAD

**Issue by gyhughes** [hay-kot/homebox#54]
### What is the problem you are trying to solve with this feature?

When registering a new user, the Register button is disabled if the password is larger than 19 characters.
This character limit is also present in the "Change Password" modal.

### What is the solution you are proposing?

Increase the password max length to 20+ characters.

### What alternatives have you considered?

Using a less complex/secure password.

### Additional context

![Screenshot](https://user-images.githubusercontent.com/7463033/195639816-32257933-12f7-48e7-a2c3-f44c37b8e8d6.PNG)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
There isn't a maximum length for the password. The issue you're likely running into is that your password contains one of the keywords we flag for security reasons 

```
const flaggedWords = ["password", "homebox", "admin", "qwerty", "login"];
```

If you're using any of these words in your password it will automatically fail the complexity requirement.

**Comment by gyhughes** [comment]
Ah you are right. I had "homebox" at the end of the password. Can either close this or change this to adding validation message about flagged words.
