### ISSUE TITLE
Photo support?

### ISSUE THREAD

**Issue by Paulie420** [hay-kot/homebox#545]
### What is the problem you are trying to solve with this feature?

I want to add photos to my entries. I see 'attachments', and can attach photos there, but I'd like PHOTO attachments to be displayed somewhere nicely in the listing... maybe the main one, or previews or something.

### What alternatives have you considered?

Allow a field for photo uploading; or, display any attachments that are PHOTOS to the listing... at the top, previews or some neat way.

### Additional context

If I missed this feature, please tell me how to access it / upload photos!! :P Thanks for the hard work!

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by CorneliousJD** [comment]
I was going to suggest the same actually, have been adding and tracking items that are "home assets" such as furniture, vacuum, etc, and would like to have stock photos of the items somewhere too, would be very nice.

**Comment by CorneliousJD** [comment]
Well, I spoke too soon, it looks like if you do add one as a photo it shows up in a special section!

![image](https://github.com/hay-kot/homebox/assets/724777/515bad2d-81c8-453d-a1fa-732f30d98da4)

**Comment by bendreality** [comment]
I would suggest to show the images in the search Section. I put together an image in Photoshop. 
Could imagine it like this :
![image](https://github.com/hay-kot/homebox/assets/27996292/540daff7-2b77-4015-9228-8aa8e385005a)

Than it's easy to find things visually while typing a searchword.

**Comment by pytlv** [comment]
+1
I submitted similar feature request here:
https://github.com/hay-kot/homebox/issues/425

Dear developers, what should we do to have it implemented?
Many thanks, and have a great week!

**Comment by timdonovanuk** [comment]
+1 to this, visual identification of assets would make this perfect :)

**Comment by hay-kot** [comment]
> I want to add photos to my entries. I see 'attachments', and can attach photos there, but I'd like PHOTO attachments to be displayed somewhere nicely in the listing... maybe the main one, or previews or something.

Pretty sure this is implement as described above. If you want them on the cards themselves, like in search. That's on the roadmap. As  such I'll be closing this to track it on the road map. 

Thanks!
