### ISSUE TITLE
Lost and Found when accessed from external IPs

### ISSUE THREAD

**Issue by andritolion** [hay-kot/homebox#547]
### What is the problem you are trying to solve with this feature?

I use Homebox inside my home network only. I also use a reverse proxy for exposing certain services in my home network to the internet. However, I would like inventory stickers created by Homebox to act differently when they are scanned from an external network. Inside my home network, the FQDN for Homebox (Homebox.myCatLAN.net) resolves to an internal IP (192.168.x.x) and on the public Internet, it resolves to my VPS's IP. If it's detected the access was through the Internet, show a lost and found page. 

### What is the solution you are proposing?

If it's detected the access was through the Internet, show a lost and found page.

### What alternatives have you considered?

Setting up own web server for lost and found. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by PhilRW** [comment]
I was going to request something similar. Perhaps homebox could display a lost and found page to unauthenticated users.
