### ISSUE TITLE
Homebox not loading after 0.10.0 update

### ISSUE THREAD

**Issue by dmontoya3** [hay-kot/homebox#584]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.0

### What is the issue you are experiencing?

I've just updated to version 0.10.0 and now the app gets stuck on the boot loading screen. 
![image](https://github.com/hay-kot/homebox/assets/41489098/9391994b-62e2-4385-9479-5796fe1ba27a)

I've tried stopping and restarting the container. I've tried multiple browsers (edge, chrome, firefox and their incognito modes). I've tried deleting cookies as well and it just won't load

### How can the maintainer reproduce the issue?

Update the main app on a docker container via portainer and then try to start the app

### Deployment

Other

### Deployment Details

I'm using docker on a Raspberry Pi and maintain my containers via Portainer

**Comment by hay-kot** [comment]
Could you try the nightly image?

`ghcr.io/hay-kot/homebox:nightly`

If that doesn't work, try clearing your cookies and reloading the page.

**Comment by dmontoya3** [comment]
How do I re-pull the image (to maintain my data) whille changing the stack version?

**Comment by hay-kot** [comment]
I don't know anything about portainer, but I don't think changing your tag should result in data loss. You should just be able to change the image field and it should update. The error is in the frontend code so moving from nightly to v0.10.0 won't cause any issues for now.

**Comment by dmontoya3** [comment]
Changing to nightly and redeploying the stack fixed the issue. This is the log in screen with the version build below

![image](https://github.com/hay-kot/homebox/assets/41489098/f1f9627f-8111-4efb-8b0c-d5cf1c13a299)

**Comment by hay-kot** [comment]
Excellent, thank you for helping me confirm this! I've just started a new build/release for v0.10.1 so that fix should be out in about an hour or so!

**Comment by dmontoya3** [comment]
Updating to 0.10.1 also causes the infinite loading bug in my case. Again tried deleting cookies and several browsers. Here is my log if it helps

![image](https://github.com/hay-kot/homebox/assets/41489098/6c414638-633e-4fbe-9c97-809c4f20ed05)

**Comment by hay-kot** [comment]
@dmontoya3 the images are still building

https://github.com/hay-kot/homebox/actions/runs/6471669171

**Comment by dmontoya3** [comment]
Now it is working with 0.10.1, thanks for your help. Keep up the good work
