### ISSUE TITLE
New quick quantity adjustment redirects to login page

### ISSUE THREAD

**Issue by vukisz** [hay-kot/homebox#585]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.10.1 ~ Build: ae4b95301f28e361ce989019656f8c78a4469cf9

### What is the issue you are experiencing?

New quick quantity adjustment redirects to login page

### How can the maintainer reproduce the issue?

Go to any item and try to use quick quantity adjustment. It just redirects to login page

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
I can't seem to replicate this anymore, could you try clearing your cookies and doing a hard refresh and see if the issue persists?

**Comment by vukisz** [comment]
Tried from fresh incognito tab. Still same. I am on mobile view of that's make difference

**Comment by kangver** [comment]
Hi,
I found the same problem.
 
 Version: v0.10.1 
 OS: Docker
 
![image](https://github.com/hay-kot/homebox/assets/56177476/58de6072-d157-49b0-a423-0d346afef0e8)

**Comment by bee-eater** [comment]
Same problem for me!
