### ISSUE TITLE
Add the possibility to have multiple projects on same instance

### ISSUE THREAD

**Issue by Kimbaras** [hay-kot/homebox#595]
### What is the problem you are trying to solve with this feature?

I'm storing various things that are not related between them (eg: one inventory instance for electrical components, one instance for miniatures, and so on).

### What is the solution you are proposing?

Having the possibility to add multiple "projects" or separated inventories into a single instance.

### What alternatives have you considered?

Currently running multiple instances / containers for the different inventories

### Additional context

A bit more of context about this, which may help better understand what I mean:

So basically I'm using your software (and by the way, I'm finally settled after checking at least two or three different solutions) for keeping an inventory of different things which are not related between them.

I'm using it for the inventory of electrical components and IOT projects, as well as using it to keep an inventory on the warhammer boxes currently stored in ceiling, and starting to implement a third instance to keep track of the 3D files.

While the container is really small and it's not so impactful on my homelab, I'd prefer having a single container to look after, so having the ability to add multiple project / inventories completing separated between them on a single instance / container would be lovely.

I know this might be a requested with a larger impact or requiring some substantial changes, but hey! one can ask no?

Thanks!

PS: about the checkboxes below the form and especially the implementing and maintain one, my experience with coding / programming is quite limited (excluding bash) but as an ex-QA turned SysAdmin, I could be helping with tests and so on (yeah I know, it's not much...) 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't something I'll implement, but there's nothing stopping you from creating multiple accounts to isolate your inventory. Each account get's their own isolated data, so you should still be able to accomplish what you want with only one container.
