### ISSUE TITLE
Timeout while uploading large attachments

### ISSUE THREAD

**Issue by Kimbaras** [hay-kot/homebox#596]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Latests (v0.10.1)

### What is the issue you are experiencing?

While trying to upload a large attachment to an item (a zip archive of 350 mb) in the container logs I get

`11:56AM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_items_attachments.go:39 > failed to parse multipart form error="read tcp 172.18.0.2:7745->192.168.1.117:56858: i/o timeout"`

And the upload fails / does not complete.
In the container settings / envs I've set 

`HBOX_WEB_MAX_UPLOAD_SIZE=2048`

Which according to the docs, should be 2GB of max upload size, if I did not misunderstood.

I've tried from multiple browsers (Edge and Chrome) with the same results.

I've tried with smaller files (up to 80 mb) and those were uploaded correctly.
The "smaller" file which failed to upload was about 120mb large.

Test files (and results):

- Zip archive 10mb: Success 
- STL file 50mb: Success
- Zip archive 83mb: Success
- Zip archive 120mb (and larger): Fail

I'd image large files were not meant to be uploaded, but it would it be possible to allow them?

### How can the maintainer reproduce the issue?

Create any item, edit it and try to upload a large file (100+ MB).

### Deployment

Docker (Linux)

### Deployment Details

Proxmox container based on Ubuntu 22.04 

2 Cores
1 GB Ram

**Comment by hay-kot** [comment]
Hey! 

This PR will expose the timeout values for HTTP operations

https://github.com/hay-kot/homebox/pull/622

Once that's release in v0.10.2 then you'll be able to configure the timeout to enable larger file uploads. 

Though large file upload isn't something I had on my radar for supporting so you I can't make any promises for reliability or anything.
