### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by Doublemyst** [hay-kot/homebox#597]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.10.1 ~ Build: ae4b95301f28e361ce989019656f8c78a4469cf9

### What is the issue you are experiencing?

I am using Bitwarden for loggin into homebox. Now it first were throwing error messages and now just hangs on login screen without letting me inside the homebox.
Here are the logfiles
3:25PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=GET path=/api/v1/status rid=8b3ec550adef/BB7pFU3gGX-000537 status=200
3:25PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=GET path=/apple-touch-icon.png rid=8b3ec550adef/BB7pFU3gGX-000538
3:25PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=GET path=/favicon.svg rid=8b3ec550adef/BB7pFU3gGX-000539
3:25PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=GET path=/favicon.svg rid=8b3ec550adef/BB7pFU3gGX-000539 status=0
3:25PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=GET path=/apple-touch-icon.png rid=8b3ec550adef/BB7pFU3gGX-000538 status=0
3:25PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=8b3ec550adef/BB7pFU3gGX-000540
3:26PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=8b3ec550adef/BB7pFU3gGX-000540 status=200
3:26PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=8b3ec550adef/BB7pFU3gGX-000541
3:26PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=8b3ec550adef/BB7pFU3gGX-000541 status=200

I have tried restarting the docker container, but it didn't help, I can't login. After attempt to create a new user, I was able to shortly login, but when I tried to add a new item, I was kicked out to the login screen and can't login anymore.

### How can the maintainer reproduce the issue?

open the homebox webui
enter email
enter password
press login

### Deployment

Unraid

**Comment by Doublemyst** [comment]
Additional infos:
After downgrading to v10.0 I was instantly logged in. Then I wanted to see if the login still works and pressed Log Out. I wasn't able to get to the login mask, as I got hundreds of error messages (something with auth header?). I think this was fixed in the version 10.1. 

Then I downgraded to version 0.92 and was able to login with my login / password without any issues.

**Comment by hay-kot** [comment]
If you're running a reverse proxy, it's likely related to 

#593

**Comment by Doublemyst** [comment]
Cookies are autocleared each time i close Firefox. I have tried in Firefox private browser (same issue) and also in Edge browser - also with the same result.

**Comment by Doublemyst** [comment]
I have changed the log level and this is the first message (even before I open the page - haven't seen it yet) I get:
```
10/23/2023
6:01:15 PM
4:01PM INF ../go/src/app/app/api/main.go:150 > Starting HTTP Server on :7745
10/23/2023
6:01:15 PM
4:01PM ERR ../go/src/app/app/api/main.go:162 > failed to purge expired tokens error="database is locked (5) (SQLITE_BUSY)"
```
I'll try to run new permissions on the DB location and restart the docker.

**Comment by Doublemyst** [comment]
This issue was an Unraid issue. As the template /data isn't autoset to appdata (maybe due to the possible size with all the images), it was set in my case on a share. 
In order to test the locked database issue, I have moved the folders to "appdata" share and was able to logout, login without any issues.
