### ISSUE TITLE
Images for 'sub-items' not loading

### ISSUE THREAD

**Issue by Rondal** [hay-kot/homebox#598]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.1 rootless

### What is the issue you are experiencing?

In the item view of an item that has child items their images are not shown. Those child items do have primary images and are shown correctly everywhere else but only have the placeholder image in the parents item view.

As they are displaying the placeholder I do think it should display the correct image.

![image](https://github.com/hay-kot/homebox/assets/217929/e79a46ad-a7d0-4c4d-8dd1-1ab9ff4ceac8)

![image](https://github.com/hay-kot/homebox/assets/217929/00b30ca6-57fb-4141-8c4b-80215059b774)

### How can the maintainer reproduce the issue?

Create an item with child items and attach pictures to all of them.

### Deployment

Docker (Linux)

### Deployment Details

Docker on Alpine, latest rootless deployed with a local dir mount for data.

**Comment by Bovive** [comment]
Experiencing this as well on an Unraid Docker deployment. The image that shows up is "no-image.jpg". Seems to work fine everywhere else, including search and under locations.
