### ISSUE TITLE
Sub/Child locations on Location view page

### ISSUE THREAD

**Issue by Serios** [hay-kot/homebox#603]
### What is the problem you are trying to solve with this feature?

Currently, the only way to view and access sub/child locations is trough Locations tree menu which is kind of difficult. 

### What is the solution you are proposing?

 It will be very useful and intuitive, if on the Location view page, there is a clickable list with sub/child locations for this particular location. A good example is the way how locations are listed on the home page. The design can be applied directly just modified a bit.

Maybe the list should be only the 1 level of childrens (direct descendants) to avoid overcrowding in the case if the nested locations tree is quite big. 

This will allow browsing trough locations to be much more easy and intuitive, since for jumping back and fort between them, one can use the list links and breadcrumb ones

### What alternatives have you considered?

None

### Additional context

None

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I'm pretty sure I already fixed this. I broke it in the latest release when I did some redesign of the pages

Does this page work as you expect it to? 

https://homebox.fly.dev/location/d40d90c2-e352-46e6-972d-8efa374e5e4f

**Comment by Serios** [comment]
@hay-kot Yes, this is exactly what I have on mind. Great job :)

**Comment by SelimOzil** [comment]
We want to see child locations under their respective locations. I see in demo it’s updated. Could we update our installed application?
