### ISSUE TITLE
Ability to export everythings with URLs - assets, labels, locations - use case with Niimbot printer

### ISSUE THREAD

**Issue by esolovyov** [hay-kot/homebox#609]
### What is the problem you are trying to solve with this feature?

There are Niimbot printers: https://www.niimbot.net/enweb/
They print on labels and support print from file (xls)

I am trying to build a process around it.
Shortly:
1. Prepare the DB
2. Export everything to excel + url
3. Print what I need from file - there is a way to quickly build a template and print all rows from the file.

The missing elements are:
- ids of the element in the export
- url of the element in the export (need a clear parameter - base url)
- support to export all object types - assets, labels, locations

### What is the solution you are proposing?

Actually as mentioned above

### What alternatives have you considered?

Manual copy of urls but it doesn't make sense

### Additional context

URLs in the QR codes need to be fixed as well - https://github.com/hay-kot/homebox/issues/564

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! I think this is something you should just use the API for. I don't think I'll be adding this to the roadmap. Thanks!
