### ISSUE TITLE
Can't Loggin / Regestraition working partial

### ISSUE THREAD

**Issue by k41c** [hay-kot/homebox#636]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.10.2 ~ Build: 8cc0f302919758044dc9ff4dc785c452364dc715

### What is the issue you are experiencing?

Hi,

I found your demo is abolute amazing. Exactly what I'm looking for. But unfortunatly I can't get it up and running. 

I can register, but the Register button keeps turning. I had a look inside the database and can see the new created user.
When I try to login, the login button keeps tuning. I changed the loglevel to trace. the following lines appear. I only made one request but see two entrys. The Browser debug network tab shows that there is no response from server. 
Additonaly: each log entry takes a long time. So seems some kind of timeut, but loading the site goes quiet fast <1sec

Output server
homebox  | 8:22AM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=61752f84f16c/ZwQXULsOyN-000100
homebox  | 8:22AM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=61752f84f16c/ZwQXULsOyN-000100 status=200
homebox  | 8:22AM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=61752f84f16c/ZwQXULsOyN-000101
homebox  | 8:22AM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=61752f84f16c/ZwQXULsOyN-000101 status=200

Browser Log
POST http://192.168.xxx.xxx:3100/api/v1/users/login net::ERR_EMPTY_RESPONSE: use-api.e520ec3d.js:1
TypeError: Failed to fetch:
    at w.do (use-api.e520ec3d.js:1:7111)
    at w.post (use-api.e520ec3d.js:1:6648)
    at I.login (use-api.e520ec3d.js:1:1214)
    at en.login (entry.b77a0acb.js:7:2712)
    at N (index.68effe32.js:1:4038)
    at entry.b77a0acb.js:1:74935
    at Ut (entry.b77a0acb.js:1:13758)
    at at (entry.b77a0acb.js:1:13836)
    at HTMLFormElement.n (entry.b77a0acb.js:1:66207)

Thanks

### How can the maintainer reproduce the issue?

version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
#   image: ghcr.io/hay-kot/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=trace
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - homebox-data:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local

### Deployment

Docker (Linux)

### Deployment Details

Debian:latest (rpi3)

**Comment by hay-kot** [comment]
Are you access with a reverse proxy? It may be an issue with secure cookies and not properly forwarding your IP/host information from the proxy.

**Comment by NefixEstrada** [comment]
I'm experiencing the exact same issue, without proxy or anything.

The logger states that returns responses to the browser, but the browser doesn't receive them. So it sends them again? And then the logger says the creation has failed. Same thing with the login:

```
8:02PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=GET path=/api/v1/status rid=809687076ced/02NYOksexc-000169
8:02PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=GET path=/api/v1/status rid=809687076ced/02NYOksexc-000169 status=200
8:03PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/register rid=809687076ced/02NYOksexc-000170
8:03PM DBG ../go/src/app/internal/core/services/service_user.go:51 > Registering new user email=admin groupToken= name=Admin
8:03PM DBG ../go/src/app/internal/core/services/service_user.go:64 > creating new group
8:03PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/register rid=809687076ced/02NYOksexc-000170 status=204
8:03PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/register rid=809687076ced/02NYOksexc-000171
8:03PM DBG ../go/src/app/internal/core/services/service_user.go:51 > Registering new user email=admin groupToken= name=Admin
8:03PM DBG ../go/src/app/internal/core/services/service_user.go:64 > creating new group
        8:03PM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_user.go:39 > failed to register user error="ent: constraint failed: constraint failed: UNIQUE constraint failed: users.email (2067)"
8:03PM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="ent: constraint failed: constraint failed: UNIQUE constraint failed: users.email (2067)" req_id=809687076ced/02NYOksexc-000171
```
```
8:06PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=809687076ced/02NYOksexc-000221
8:06PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=809687076ced/02NYOksexc-000221 status=200
8:06PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=809687076ced/02NYOksexc-000222
8:06PM INF ../go/src/app/internal/web/mid/logger.go:41 > request finished method=POST path=/api/v1/users/login rid=809687076ced/02NYOksexc-000222 status=200
8:06PM INF ../go/src/app/internal/web/mid/logger.go:36 > request received method=POST path=/api/v1/users/login rid=809687076ced/02NYOksexc-000223

```

**Comment by k41c** [comment]
Hi sorry, I had no time to get back. I retry with 0.10.3 and now it's working as expected.

Thanks for the support!
