### ISSUE TITLE
Blue 404 page when trying to export inventory over Apache proxy

### ISSUE THREAD

**Issue by terba** [hay-kot/homebox#640]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.2

### What is the issue you are experiencing?

Behind an Apache 2.4 proxy I get a blue screen of 404 when I click on *Export Inventory* button. The same happens on the official demo site too at https://homebox.fly.dev/tools
Opening attachments or downloading them has the same result. Photos work and everything else works.
With direct access to my homebox host there is no problem at all.

### How can the maintainer reproduce the issue?

My apache virtual host is very basic:
```apache
<VirtualHost *:443>
    ServerName mydomain.org:443

    ... ssl cert file settings ...

    ProxyPreserveHost On

    ProxyPass / http://homebox.internal:7745/
    ProxyPassReverse / http://homebox.internal:7745/
</VirtualHost>
```

### Deployment

Other

### Deployment Details

Just started the downloaded binary in the shell for evaluation purposes

**Comment by pogora** [comment]
Same here. Tried it on my server (deployed with Docker) and on the Demo site. Same 404 Error. 
Only works if the site is accessed through http / unencrypted.

**Comment by Bovive** [comment]
The same thing is happening for attachments. All of my attachments give 404 using SSL reverse proxy. Works fine on http. I was able to replicate this on the demo site as well.

**Comment by hay-kot** [comment]
If you refresh the page that 404's does it work?

**Comment by Bovive** [comment]
> If you refresh the page that 404's does it work?

Looks like a force refresh (Control+F5) does work. If I close it and open it again, it goes back to 404 and have to force refresh again.

**Comment by hay-kot** [comment]
@Bovine thanks! I found the underlying issue, should be fixed in nightly and the next release.
