### ISSUE TITLE
Product images are shown as "missing" image in browser

### ISSUE THREAD

**Issue by bee-eater** [hay-kot/homebox#659]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.10.2

### What is the issue you are experiencing?

After some time, all images are shown as broken links / broken images.

### How can the maintainer reproduce the issue?

Not sure, it somehow seems connected to the cookies. If I delete all cookies it works again. Probably you could try messing with them...

### Deployment

Docker (Synology)

**Comment by bee-eater** [comment]
It seems that the attachement token is somehow missing and is only recreated when loggin in  freshly.

**Comment by hay-kot** [comment]
I think this is fixed in the latest release v0.10.3. Could you try and replicate the issue on there?

**Comment by hay-kot** [comment]
Closing with the assumption this is fixed. If you clear your cache and it's still not working please open another issue. Thanks!

**Comment by bee-eater** [comment]
Seems fixed, thanks a lot :-)
