### ISSUE TITLE
404 error page when trying to open attached pdf file

### ISSUE THREAD

**Issue by lucasarrudadev** [hay-kot/homebox#661]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

3.4

### What is the issue you are experiencing?

Under an Item, after uploading an attachment in pdf format (as Manual for example) and trying to open it homebox goes to 404 not found page

### How can the maintainer reproduce the issue?

1. Create an item
2. Upload an pdf attachment to this item as manual
3. Save the item
4. Try to download or open the pdf attachment

### Deployment

Docker (Windows)

**Comment by branehaven** [comment]
I had this same issue and I was able to resolve it by logging out and logging back in.

**Comment by Suyooo** [comment]
Same problem here, all attachments end on a 404. Photo attachments work on the site, but once I click download or open, they also end up as a 404.

Firefox 121, running Homebox via the rootless Docker image.

Logging out and in again did not work for me, but disabling the service worker does. Apparently, something in there is broken - if I block it or disable it temporarily by hard-refreshing the attachment page with Ctrl+Shift+R, all attachment links work fine.

**Comment by hay-kot** [comment]
This was fixed in 

- https://github.com/hay-kot/homebox/commit/f2363b85cb71e776d685527d10525b4e75e16883

The fix will be in the next release (sometime before the new year), or you can upgrade to the nightly tag or use one of the work-arounds posted. 

Thanks!
