### ISSUE TITLE
Concurrency issues with SQLite

### ISSUE THREAD

**Issue by zebrapurring** [hay-kot/homebox#669]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.10.2 ~ Build: 8cc0f302919758044dc9ff4dc785c452364dc715

### What is the issue you are experiencing?

I have been doing some testing using the API to automate adding and modifying items in bulk. Keeping the browser window open with the websockets listening for events is usually enough to trigger errors that seem related to accessing the database concurrently:

```

12:36AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="database is locked (5) (SQLITE_BUSY)" req_id=4462b1284046/Li18wcT5KQ-000028
```

The errors I get are usually related to the authentication being unable to verify my session, but a few times I was able to corrupt the database just by having a reader (the web UI) and a writer process (the script accessing the API - which is not even making parallel requests).

### How can the maintainer reproduce the issue?

1. Start instance of the app
    ```sh
    docker run --rm --publish 3100:7745 ghcr.io/hay-kot/homebox:latest --log-level trace
    ```
2. Create user
3. Log in with the newly created user with the browser
4. Create 50 items concurrently
    ```sh
    for i in $(seq 1 50); do curl -X POST http://localhost:3100/api/v1/items -d '{"name":"dummy","locationId":"4d52b319-1d18-4b36-ba21-191628ae73ae"}' -H "Authorization: Bearer AEBR2IR2IINOJPRZJ6KLR36WLY"& done
    ```
5. The frontend receives error code 401 Unauthorized and logs the user out

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
THANK YOU!

This bug report with specific reproduction helped me track down an issue that I've been seeing for what feels like months. 

This will be fixed in the next release! 🚀
