### ISSUE TITLE
The database does not support NULL purchase/sold prices

### ISSUE THREAD

**Issue by itaegeemuenchen** [hay-kot/homebox#680]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.10.2 ~ Build: 8cc0f302919758044dc9ff4dc785c452364dc715

### What is the issue you are experiencing?

When a purchase/sold price is unknown, it should not be stored as zero. Likewise, having a purchase/sold price of zero should be a valid use case, and the price should be displayed in the list of fields.

One possible solution would be migrating the database columns to allow `NULL` values.

### How can the maintainer reproduce the issue?

Trying to save an item without a purchase price returns error 500 Internal Server Error.

At the same time, when saving an item with purchase price value of 0 the purchase price is not displayed in the list of fields.

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
> When a purchase/sold price is unknown, it should not be stored as zero. Likewise, having a purchase/sold price of zero should be a valid use case, and the price should be displayed in the list of fields.

Besides _correctness_ is there is use-case that this prevents you from doing? I don't really want to deal will Nulls if I don't have to. 

If i just changed the behavior so the purchase price always shows is the purchase date is provided, would that be sufficient?

**Comment by itaegeemuenchen** [comment]
> Besides correctness is there is use-case that this prevents you from doing? I don't really want to deal will Nulls if I don't have to.

We do have some items that have a purchase prize of zero (donations or free stuff, for example) and also items that we don't know the purchase price (and we would like to revisit them later on to fill out the actual purchase price).

The problem is having both values stored as `0` we can't tell which ones _actually_ cost zero, or in which ones the field just wasn't filled out...

> If i just changed the behavior so the purchase price always shows is the purchase date is provided, would that be sufficient?

Unfortunately not, since for our use case we query directly the database/API.

**Comment by hay-kot** [comment]
Hey! I don't think this is something I'm going to work on. As a work around you could use a negative value to indicate null, if that works for what you're trying to do. 

Since it sounds like you're using this for a business, if you interested in sponsoring the development of this change I'd be happy to talk about that. Feel free to reach out. 

Thanks!
