### ISSUE TITLE
[FR] Different SQL backend

### ISSUE THREAD

**Issue by userbradley** [hay-kot/homebox#683]
### What is the problem you are trying to solve with this feature?

I plan to run this at home on my Kubernetes cluster (and then give the helm chart to the community) but the SQLite Database means I cant run more than one replica on my cluster before I have issues with storing the database

### What is the solution you are proposing?

I am proposing that you (the amazing dev <3 ) consider implimenting a database like mysql or Postgresql

### What alternatives have you considered?

Crying my self to sleep

### Additional context

I've been looking for something like this for ages, so I really hope this app gets sql support outside of sqlite!

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! Thanks for the feature request. I don't think I'm going to implement this.

While we do use an ORM the manage the database, we also do SQL migrations and custom SQL in a few places and supporting multiple instances would require significant work on my end for

1. Cross SQL implementation migrations/queries
2. New testing for multiple SQL backends

Sorry!
