### ISSUE TITLE
Automatically set Primary Photos.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [hay-kot/homebox#688]
### What is the problem you are trying to solve with this feature?

Currently, if I add an image, I have to it as a primary photo via the settings every time. 

### What is the solution you are proposing?

If a photo is added, automatically set it as primary product image.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by willyyr** [comment]
Have you tried the option under "Tools" to set the primary photo to the first image added as photo? It's still a workaround to what you are asking which would be useful as well but can help you after adding a bunch of items and photos to ease the "pain".
![image](https://github.com/hay-kot/homebox/assets/1862593/dddaf901-b5d1-4af1-9bf2-6b2c9bff033d)

**Comment by Jas-SinghFSU** [comment]
I'm currently doing that which really does ease some of the pain. Usually my process is to inventory a bunch of items and then assign primary photos at the end. But have a setting to make that default behavior would be wonderful!

**Comment by hay-kot** [comment]
FYI, this has already been fixed and merged into main. It will be in the next release.

**Comment by Jas-SinghFSU** [comment]
Awesome, thank you! BTW, Homebox is amazing.
