### ISSUE TITLE
Maintenance Tasks, Intervals, Reminders with Log

### ISSUE THREAD

**Issue by bladecoates** [hay-kot/homebox#69]
### What is the problem you are trying to solve with this feature?

Set up maintenance tasks, intervals and reminders. 

Use cases:

1.) I live in a hurricane-prone area and have generators. Would be nice to be able to add my generator as an asset and then define maintenance tasks for it with intervals for the tasks and reminders when the defined interval passes. Change oil every X months or hours.

2.) Smoke/CO Detectors - Change batteries every year. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! That's already part of the long-term plans for this. I haven't given it too much though with the structure, but I'm very open to contributors and ideas of this.

Here's the main issue 

- #14 

Looks like you're interested in contributing, let me know how I can support of help you out!

**Comment by hay-kot** [comment]
Closing since we're tracking in #14
