### ISSUE TITLE
Search item with a picture

### ISSUE THREAD

**Issue by julienpmorand** [hay-kot/homebox#693]
### What is the problem you are trying to solve with this feature?

Suppose a person finds an item and wonders where it goes, but doesn't know how it's called. Instead of searching with a keyword, having the ability to search by taking a photo of the item would be pretty cool.

### What is the solution you are proposing?

I think that first, all the images from the database (as well as the upcoming ones) should go through some image-recognition API (preferably an open source one), then would return a list of keywords.
Then when taking a picture, you'd get another list of keywords and perform a keyword search compared with the list of keywords of the other images and return the results.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! I think this extends outside of the aim of Homebox. While it's a cool idea, I think it's probably better implemented via a mobile app and use some 3rd party API that then integrates into Homebox. We have an Open API and would hapily consider some additions to enable that find of workflow from another app. 

Realistically, I don't plan to add any 3rd party integrations into Homebox.

**Comment by julienpmorand** [comment]
Fair enough, thanks!
