### ISSUE TITLE
Word matching in location dropdowns

### ISSUE THREAD

**Issue by hklown** [hay-kot/homebox#703]
### What is the problem you are trying to solve with this feature?

Currently (as of 0.10.3), when searching for a location in dropdowns (i.e. when setting the property in an Item, but there may be other applicable places), matching/filtering is done based on a perfect match from the start of the string. As an example, if you have a location called "Closet" and a location called "Entry Closet", typing "Closet" in the location field to filter will only return "Closet", not "Entry Closet":

![Example](https://github.com/hay-kot/homebox/assets/748226/a4d58842-3219-4dd3-bdaf-a9b81f308d16)

### What is the solution you are proposing?

Searching/filtering for locations should match against individual words in a location/label, and not a full match against the location name. Therefore, a search for "Closet" would match "Entry Closet", "Hallway Closet", "My Closet", "Wife's Closet" etc etc.

### What alternatives have you considered?

I guess I could just rename things like "Closet (Entryway)" but that seems a bit less natural.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by mdjhnson** [comment]
I second the need for this feature. As I add more and more locations and sub-locations to Homebox, having a non-exact search eases the creation process.

Currently, it is almost easier for me to find the location first and then add items from the location instead of just creating an item from the home page. 

I am fine with how it currently functions. It's just something that I have to keep in mind as I'm adding items. However, I doubt my wife would be so forgiving. She just won't add items 😭.

**Comment by hay-kot** [comment]
Hi! 

I merged the work for this in this PR:

- #800

I see that you said your willing to sponsor this development, if that's still the case you can sponsor that work here https://github.com/sponsors/hay-kot#sponsors. Your support is greatly appreciated! 

## Example

![image](https://github.com/hay-kot/homebox/assets/64056131/0c2faaa4-5824-451c-a51d-6e03f8fd0813)

**Comment by mdjhnson** [comment]
Thanks for taking care of this! I also just realized that I wasn't sponsoring you as I thought. I love Mealie but I'm personally more interested in Homebox. Thanks for your work @hay-kot!

**Comment by hklown** [comment]
Sent some extra bones your way in addition to my tiny monthly contribution. Thank you for implementing this feature!
