### ISSUE TITLE
Attachments/documents linked to external URLs

### ISSUE THREAD

**Issue by jpbaril** [hay-kot/homebox#704]
### What is the problem you are trying to solve with this feature?

I use [Paperelss-NGX](https://github.com/paperless-ngx/paperless-ngx) to store receipts/manuals/etc. and so would prefer to keep all my documents in there. Yet, I would want to reference those external documents in Homebox items.

### What is the solution you are proposing?

My first thought would be that when adding an "attachment" Homebox would allow to choose between uploading a file to Homebox (as it is right now) or simply link to an external entity/URL.

That way Homebox could continue to reference these external entities as per the usual attachment types (i.e. photos, receipt, warranty, etc.) and so show/use them just like those uploaded to Homebox.

### What alternatives have you considered?

I could create each time a custom field for receipts+manuals+etc. and input the external URLs since custom fields allow URL links, but that would not be "clean" and Homebox would not understand "system-wise" what those linked entities are (i.e. receipts/manuals/etc).

### Additional context

My proposition is really just a general idea / concept, there is maybe a better way to achieve the same goal.

Thank you

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! 

I'm sympathetic to this viewpoint. In a perfect world where I had more time, or there were more maintainers for this project I'd like to support this. I think it the integration was good, I would even use it. 

That said, I just don't have the time to manage or maintain this integration and keep up with any API changes that come from a 3rd party dependency. 

As a small alternative, you could use a custom field to link to a specific document or tag in Paperless to help keep the two organized. If you use a URL or the markdown syntax for a link you'll get a nice button as well. 

![CleanShot 2024-01-18 at 13 52 36@2x](https://github.com/hay-kot/homebox/assets/64056131/1fe5329d-cf42-4b4e-b83f-6d58a88808ce)

**Comment by jpbaril** [comment]
As mentioned in the "alternative considered" using custom fields is not adequate enough. Especially, when there might be multiple linked documents for an item it could become quickly messy.

Maybe it's not the best way to go, but in my mind I was not envisioning any API calls at all. All I was suggesting is that the "add an attachment" feature in Homebox could allow to choose between either uploading a file in Homebox (like it is right now) or simply inputing manually an URL (a bit like a custom field). In latter at least Homebox would understand what the link represents and list it as such in the attachment list.

**Comment by hay-kot** [comment]
I don't really see how it's that different than using the existing functionality for links/custom fields. You could also add them as a section in the Notes using markdown.

This isn't something I'm going to work on, however I would review a PR that implements a link style attachment being added provided there's sufficient test coverage.
