### ISSUE TITLE
Environment Variable to disable: Login Page, Warranty, & All References to $$

### ISSUE THREAD

**Issue by K-J-VV** [hay-kot/homebox#714]
### What is the problem you are trying to solve with this feature?

I'm interested in using Homebox to keep track of things that I don't particularly care about the cost/sale/warranty (i.e., air filters, oil filters, water filters, etc.). In this particular use case there's no need to have any reference at all to the cost/sale/warranty. All these features just add more bulk/scrolling clicking. Would be great from a UI perspective to be able to disable these if not needed. Since I'm only concerned about expirations, would be nice to be able to change where the word "Warranty" appears to "Expiration"

I'm also not particularly concerned about security for this data. Having an admin account to be able to modify things is necessary, but once setup I'd just like to be able to access/view Homebox without the requirement of logging in. I'd also like to setup for my parents & any way to make it easier for them to use would be great lol

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! 

These all seem pretty specific to you workflow. I'm not super interested in supporting these types of feature flags. I'd suggest either forking the project and making those changes on your own, or finding another project that fits your needs a bit better.
