### ISSUE TITLE
Renaming a location does not refresh the "Create Location" and "Create Item" form "Parent Location" dropdown

### ISSUE THREAD

**Issue by sk8rsdad** [hay-kot/homebox#718]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.3

### What is the issue you are experiencing?

The Parent Location dropdown retains stale information.

### How can the maintainer reproduce the issue?

1. Select an existing location, edit the name, and save.
2.  Click **+ Create** to create a new location.
3. Enter a name and try to assign a parent.
4. The parent list shows the old value.
5. Rinse and repeat fot the "Create Item" form.

A workaround to force the new name to appear is a browser refresh of the page.

### Deployment

Docker (Synology)

**Comment by DrMaxNix** [comment]
This also happens when you create a new location; You can't use the new location to create new items until refreshing the page.

**Comment by hay-kot** [comment]
Are there any errors in the console in your browser after you update?

We use a websocket connection to sync changes. If your proxy is denying websocket connections that could be a problem.

**Comment by sk8rsdad** [comment]
> Are there any errors in the console in your browser after you update?
> 
> We use a websocket connection to sync changes. If your proxy is denying websocket connections that could be a problem.

Thanks for the speedy investigation.

There were websocket errors. 

I'm running through a reverse proxy. After enabling the websocket headers there are no longer errors in the console but the problem persists. Adding, changing, or deleting a location is reflected immediately on the Locations main page but the _Parent Location_ dropdown shows stale data.

**Comment by DrMaxNix** [comment]
Can confirm this. My reverse proxy also has issues with ws tunneling, so I tried directly connecting without the proxy, can confirm that new the ws connection works, but the problem persists. It is even doing a GET request to `api/v1/locations?filterChildren=false` which already lists the new location; It is not shown at the dropdown though.

**Comment by jh83** [comment]
I have the same issue. If i add a new location, then it doesn't become visible when i try to choose it as a parent for the next new location until i refresh the web page.

I access the server (docker) directly without any firewall or proxy in between and the web browsers debub console does not indicate any error.
