### ISSUE TITLE
Option for 100% self hosted without external resources

### ISSUE THREAD

**Issue by DO1JLR** [hay-kot/homebox#748]
### What is the problem you are trying to solve with this feature?

Homebox is a great inventory system for self-hosting. However, I would prefer not to include external resources in a self-hosted variant. As far as I have seen, elements from api.iconify.design are included. I would like to do without something like that.

### What is the solution you are proposing?

The iconify documentation states that the service can also be self-hosted. So it would be cool if you had the option of using your own iconify api, for example.

### What alternatives have you considered?

A variant that works completely without the iconify API would of course also be an interesting consideration, but I suspect that this could be more work.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.

**Comment by hay-kot** [comment]
100% 

Fix would be to replace existing icons with this library 

https://github.com/unplugin/unplugin-icons

These will get compiled into the build so no need for external services.

**Comment by colbach** [comment]
Oh, I didn't even knew they were using such external components. I really hope that they change this because this is really a deal breaker. Does anyone know what happens when the service is not reachable?

**Comment by virtadpt** [comment]
@colbach Graphical elements - icons - won't show up when a page loads.  No SVG files, no CSS that tweaks the SVG icons (backgrounds, transparency, shading).  Whatever iconset plugins added on won't load.  In short, broken UI.

**Comment by colbach** [comment]
For me an much bigger problem is that this binds the lifespan of an external service onto the lifespan of this app. I mean, if homehox is discontinued one day and then this service disappears, it will break the self hosted service. I don't want to put years of work into entering data just to find out that I can not run it anymore. If the software is abandoned but self contained, I will always have the option to spin it up on an old linux version and use it in an VLAN where no other malicious device in my network can access it.

**Comment by colbach** [comment]
@virtadpt Why would this relevant whether it is? It is relying onto an external service without real necessity. This makes it impossible to redeploy old code in >20 years when the service long gone. What is the point of self hosting when relying on hosted services anyway? This means (1) need internet, (2) rely on an external provider and (3) loose the reproducibility.
