### ISSUE TITLE
Two factor authentication (2FA) support

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#756]
### What is the problem you are trying to solve with this feature?

Would like to be able to add two factor authentication (2FA) to harden the login security. 

### What is the solution you are proposing?

Implement 2FA support via email OTP.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Duplicate

- https://github.com/hay-kot/homebox/issues/61
