### ISSUE TITLE
A more robust backup engine 

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#758]
### What is the problem you are trying to solve with this feature?

The ability to back up data committed to Homebox. 

### What is the solution you are proposing?

A backup functionality to complement the export functionality. 

Generating a backup could produce a zipped archive with folders for all data stored in the database. 

For instance:

-> Assets export (already implemented)
-> Locations export (not yet implemented)
-> Attachments export (not yet implemented)

A further addition could be a cloud sync functionality to upload the generated backup directly to a cloud service (e.g. B2 or S3).

### What alternatives have you considered?

I'm thinking about the best way to back up the data I'm committing into my HomeBox instance and so far the best idea I have is automatically backing up the container. But it's a flawed methodology. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I won't be implementing a backup engine within the application. I did that for Mealie (the other self hosted app I authored) and regret it. It's too difficult to manage all of the edge cases and manage cross version restores. 

You are much better off backing up the volumes/files directly. The great thing about Homebox is it just uses SQLite and the file system so it's super easy to backup with whatever you like.
