### ISSUE TITLE
File extension is editable when editing attachment title

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#76]
## First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

## Homebox Version

v0.2.0

## What is the issue you are experiencing?

When editing an attachment title, the file extension can also be changed (or removed).

While the name and file extension of an attachment is not changed in the docker data volume, it is on the frontend. As such a user can edit an attachment title to remove the file extension, making it un-openable when downloaded.

### File in docker data volume
![image](https://user-images.githubusercontent.com/4337361/195963589-30ba9fc4-1f9b-4dee-990a-4d3c33449a7e.png)

### Attachment title updated, manually retaining extension
![image](https://user-images.githubusercontent.com/4337361/195963628-2381cb12-6ab2-49a2-97b7-4c50ce1fdccd.png)

### Attachment title updated, changing extension
![image](https://user-images.githubusercontent.com/4337361/195963652-b78875d7-e313-4ef2-b53b-b27972db0d23.png)

### Attachment title updated, removing extension
![image](https://user-images.githubusercontent.com/4337361/195963675-144775b5-0aaf-4e5c-8eef-e8137d3658fe.png)

The proposed solution would be to remove the extension from the attachment title, to stop people from accidentally removing or changing it.

## How can the maintainer reproduce the issue?

1. Upload an attachment to an item
2. Edit the attachment title, removing or changing the extension
3. Download the file

## Deployment

Docker (Windows)

**Comment by hay-kot** [comment]
#161 fixes this issue. We'll allow to use to edit the file extension since that is saved as the document title after creation. However when the file is downloaded, we first check to see if the title has an extension, otherwise we assign the extension of the file path.
