### ISSUE TITLE
Support for different barcode types

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#761]
### What is the problem you are trying to solve with this feature?

Currently the system automatically generates QR codes for each object created. 

However, users do not have the ability to choose to use a different barcode symbology for inventory tracking. 

### What is the solution you are proposing?

1. Provide users with the option to choose between QR, DataMatrix, Aztec and any other symobology that can fit a URL in a reasonabley sized barcode.
2. An additional barcode configuration option might be providing users with the ability as to what to include in the automatically generated QR codes. For instance rather than include the URL string, they could also include the asset/location ID as a line of text (etc).

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I don't think we're going to implement this. QR codes serve the purpose for most if not all home users. These feels like more of business use case than anything else. 

If you need this for a business purpose you can reach and I can provide you a quote to implement this in a custom version.
