### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#763]
### What is the problem you are trying to solve with this feature?

Consider this scenario (perhaps not totally unrealistic):

-> You're moving apartment 
-> You've miraculously managed to find movers who are onboard with the idea of scanning QR codes to figure out where to put your boxes 

You want the movers to be able to:

-> Access the system to follow the links

But:

- You don't want the movers to be able to edit or delete the data (through accidental deletion or otherwise).

One possible solution:

User type with read only access to the system.

### What is the solution you are proposing?

Implement a user type with read only access in order to be able to access and view the inventory stored in the system without the ability to modify it. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Thanks for the request, I don't think this is a real world scenario that we need to worry about here. Perhaps if someone comes back with a real world use case we can revisit this.

**Comment by kimzrn** [comment]
i have two exempel in mind
1. for family member how for different reasons shouldn't have full access but still moves thing or/and lending out ting and more
2. as read access to other apps
