### ISSUE TITLE
Asset IDs: ability to generate a random identifier 

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#764]
### What is the problem you are trying to solve with this feature?

Currently the numbering system for asset IDs starts with 000-001. I believe that if you were to try force the system to start with a different starting number (say 0321) it would not continue sequentially with further asset IDs (e.g. automatically create the next item with ID 0322).

### What is the solution you are proposing?

To increase flexibility, it would be nice to:

-> Be able to configure a different asset ID starting number. For example for people who are migrating from an existing inventory management system and they've already assigned IDs to everyTO increasthing up to 103 .. start generating asset IDs from 104. 

-> Be able to choose between sequential asset IDs and random identifiers which would populate randomly at each asset generation, without duplication. 

-> Be able to choose between different systems for asset IDs. For instance, four upper case characters (XDSE), numbers only, 3 digits, 4 digits. Etc. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
> Be able to configure a different asset ID starting number. For example for people who are migrating from an existing inventory management system and they've already assigned IDs to everyTO increasthing up to 103 .. start generating asset IDs from 104.

We just take whatever the highest asset ID is and +1 to that so if you want to do this all you need to do is create an item and set the Asset ID to whatever you want to increment from.

> -> Be able to choose between sequential asset IDs and random identifiers which would populate > randomly at each asset generation, without duplication.
>
> -> Be able to choose between different systems for asset IDs. For instance, four upper case characters (XDSE), numbers only, 3 digits, 4 digits. Etc.

I don't know what real world use case this would solve. Do you have a specific problem that you're experiencing?

**Comment by danielrosehilljlm** [comment]
@hay-kot 

The four letter identifiers printed beneath a QR code system is quite commonly used in some "ready to roll" type home management systems so I figured it just might be something that people are already familiar and comfortable with.

But you're correct ... no burning need (especially as the functionality you described above seems perfectly sufficient!)

![qr codes](https://github.com/hay-kot/homebox/assets/40233203/e474da97-151e-457f-bcbc-25ed354d046c)

**Comment by hay-kot** [comment]
Thanks for following up, going to close since there isn't a clear use case here. Thanks!
