### ISSUE TITLE
Adding Malaysia Currency MYR

### ISSUE THREAD

**Issue by kii-rinn** [hay-kot/homebox#765]
### What is the problem you are trying to solve with this feature?

No Malaysia currency selection

### What is the solution you are proposing?

To allowing user from Malaysia to use MYR currency

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This is fixed in the next release with the new user defined currency 

- https://github.com/hay-kot/homebox/issues/695
