### ISSUE TITLE
Implement searching by asset ID

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#769]
### What is the problem you are trying to solve with this feature?

Many HomeBox uses have deployed the system on their local environments. In this case, the QR codes will only "work" while the user is on the LAN. 

There are situations in which a user many wish to look up a piece of inventory remotely (from the WAN). In this case, knowing the asset ID would be an obvious way to find the catalog entry. 

Searching by asset ID, however, does not appear to currently be supported. 

![3](https://github.com/hay-kot/homebox/assets/40233203/528c7988-73d3-4dae-98a9-5b99e78c80a8)

![1](https://github.com/hay-kot/homebox/assets/40233203/40f11191-f486-4348-871b-a3c6bca07a29)
![2](https://github.com/hay-kot/homebox/assets/40233203/c184cbc1-b3d7-45d0-adf6-0a8f41033c8a)

### What is the solution you are proposing?

Add the ability to retrieve results by searching for the asset ID

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This is already implemented, 

![CleanShot 2024-02-15 at 10 10 00@2x](https://github.com/hay-kot/homebox/assets/64056131/e871eb4b-2f6c-4f45-86e4-b5707c645995)

**Comment by danielrosehilljlm** [comment]
apologies!

**Comment by hay-kot** [comment]
No worries, never hurts to ask! Thanks for you're interest in the project!

❤️
