### ISSUE TITLE
Please add Omani Rial OMR currency 

### ISSUE THREAD

**Issue by Alshukaily** [hay-kot/homebox#776]
### What is the problem you are trying to solve with this feature?

Hello,
I just started my home box and I noticed that OMR "Omani Rial" currency is not included. It would be much appreciated to add it or let me know if there is a way to add myself.
Thank you for this great project. 

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
This is fixed in the next release with the new user defined currency 

- https://github.com/hay-kot/homebox/issues/695
