### ISSUE TITLE
The ability to tag other users / conversations

### ISSUE THREAD

**Issue by danielrosehill** [hay-kot/homebox#780]
### What is the problem you are trying to solve with this feature?

Instances in which flatmates or family members share access to a common inventory management system and might wish to notify one another about items. "Yo Joe, did you drink a beer from my six pack which had the asset ID 49839"? Etc. 

### What is the solution you are proposing?

More seriously, add the ability to tag other users so that you can notify one another about "stuff" ("I found this in my storage. Do you still want it?")

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't something I'm going to implement, maybe if I had a paid/business sponsor to fund some of these bigger features we could revisit this. Thanks for the interest!
