### ISSUE TITLE
Output current size of data volume (for managing infra, backups, etc)

### ISSUE THREAD

**Issue by danielrosehill** [hay-kot/homebox#781]
### What is the problem you are trying to solve with this feature?

An idea for a feature:
In "Tools", output the current size of the data folder (e.g. "User data size: 1.2GB")
This would be useful for those who are trying to optimise the infrastructure backing their HomeBox instance. 
Additionally for planning backups, it would be useful to know how much data you currently use - as the data volume is the logical target for backuips.

### What is the solution you are proposing?

Add an output of the size of the data volume to the 'Tools' screen

### What alternatives have you considered?

You can calculate this manually through your infrastructure provider but it would be more convenient to be able to see this directly within HomeBox

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't something I'm going to implement, I think that since everything is stored on disk and if you're implementing a backup, you would have access to that file system, you would already have easy access to the size and we wouldn't be required to maintain any of that. Thanks for the idea!
