### ISSUE TITLE
add chinese

### ISSUE THREAD

**Issue by gaodaxiaya** [hay-kot/homebox#787]
### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
There is no information in your issue to indicate what you're asking for, so I'm going to close it.
