### ISSUE TITLE
Show Empty on item page not working as expected

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#80]
## First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

## Homebox Version

v0.2.0

## What is the issue you are experiencing?

The **Show Empty** selector on item pages is not working as expected. Rather than showing and hiding empty fields, it is showing and hiding empty (_see below_) sections.

However, it doesn't show and hiding empty sections correctly either. The current behaviour is:

### Item details (_Not working as expected_)

- Shows entire section at all times

### Attachments (_Working as expected_)

- Only shows section if there is an attachment

### Purchase (_Not working as expected_)

- Will show entire section if **Purchased From** is entered and/or when **Purchased Price** > 0
- Will not show section if only **Purchase Date** is entered

### Warranty (_Not working as expected_)

- Will show entire section if **Warranty Expires** is entered
- Will not show section if only **Lifetime Warranty** or **Warranty Details** are entered

### Sold (_Not working as expected_)

- Will show entire section if **Sold To** is entered and/or when **Sold Price** > 0
- Will not show section if only **Sold Date** is entered

## Expected Behaviour

The expected behaviour is that when **Show Empty** is selected, all fields will show, and when it is not select, only fields with a value or > 0 will show.

### Fields not showing, with data entered, with Show Empty not selected
1. Create a new item
2. Edit the item
3. Enter only these fields: **Location**; **Name**; **Purchase Date**; **Lifetime Warranty**; **Warranty Details**; **Sold Date**
4. Save
5. Unselect **Show Empty**
6. Only the **Details** section will show

and;

### Empty fields showing, with Show Empty not selected
1. Create a new item
2. Edit the item
3. Enter only these fields: **Location**; **Name**; **Purchase Price**; **Warranty Date**; **Sold Price**
4. Save
5. Unselect **Show Empty**
6. All sections _(bar attachment)_ will show, including empty fields

## Deployment

Docker (Windows)

**Comment by BCNelson** [comment]
I think that this is in nightly
