### ISSUE TITLE
Feature: Add i18n support

### ISSUE THREAD

**Issue by DoraTiger** [hay-kot/homebox#807]
### What is the problem you are trying to solve with this feature?

The project is now just have English language, I'm trying to add i18n support

### What is the solution you are proposing?

i18n support for web page.

### What alternatives have you considered?

Add @nuxtjs/i18n package to support muti language. Just modify the frontend, add translate file at `/frontend/lang/` ,now support English and Chinese. I have already pull requests #799 .

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [X] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by enjor00** [comment]
We need Chinese!

**Comment by hay-kot** [comment]
Dupe 

- https://github.com/hay-kot/homebox/issues/152
