### ISSUE TITLE
Specify date format in user profile

### ISSUE THREAD

**Issue by Motordom** [hay-kot/homebox#81]
### What is the problem you are trying to solve with this feature?

When editing dates on an item, they show in my local format dd/mm/yyyy
![image](https://user-images.githubusercontent.com/4337361/195967200-747d1e38-0238-44f6-9d95-dc6360e30ef1.png)

However when viewing dates, they show in US format, mm-dd-yyyy
![image](https://user-images.githubusercontent.com/4337361/195967215-4fb2d9e4-5c8f-4fd4-8d91-1501d5d5a311.png)

### What is the solution you are proposing?

Add the option in the user profile page to specify how dates should be formatted.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
in #251 I've changed all date formats to be YYYY-MM-DD. Since this is a universal format I don't think this feature requests is necessary anymore. 

If you'd still like to see support for this please write up a more detailed explanation of why we should provide this, thanks!
