### ISSUE TITLE
Search by partial item GUID (item ID)

### ISSUE THREAD

**Issue by ronindesign** [hay-kot/homebox#834]
### What is the problem you are trying to solve with this feature?

I label boxes based on their ID rather than what the box is used for since that may change from time to time. I don't want to have to create, print, and re-add a new QR code to the box every time I change the contents/purpose of that box.

Currently, I'm unable to search by any sort of "box ID" and instead have to use name or label which is more of a description of what that box is being used for at the moment.

### What is the solution you are proposing?

Search by entering part of the item GUID (i.e. item ID, same GUID that shows in the page URL when viewing an item.) This way I can put the last 5 characters of the GUID on the box and always be able to search for that box rather than having to use QR code every. This also allows me to keep names description instead of using Box 01, Box 02, Box 03, etc and then allow for renaming boxes whenever contents change.

### What alternatives have you considered?

I could name all my boxes incrementally and use that for the label, but then this hinders searchability and readability in the homebox app. I could always just use the QR code, but this is slow if I have a stack of say 5 boxes, where I could just change a few characters in the search bar instead of rescanning each QR code.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by ronindesign** [comment]
AssetID is pretty close functionality for quick lookup, but it doesn't seem we can search by AssetID.

Maybe having "search by partial AssetID" as part of the search functionality would help as well.

**Comment by hay-kot** [comment]
You can search by Asset ID

![CleanShot 2024-03-03 at 12 53 33@2x](https://github.com/hay-kot/homebox/assets/64056131/4c5768f5-d78d-4ce9-8f2d-3530d4b2ea7d)

**Comment by hay-kot** [comment]
Closing this since I think Asset ID search gets the job done here. Thanks!
