### ISSUE TITLE
Remove Hours from all "times since" or "times until"

### ISSUE THREAD

**Issue by WoosterInitiative** [hay-kot/homebox#837]
### What is the problem you are trying to solve with this feature?

Meaningless and often "wrong" (based on time-zone) values for "time since" or "time until" for all dates. For example, if I say I purchased something on today's date, it will show a meaningless "4 hours ago." It also seems to disregard my local time zone.

I've had things show as in the future because of time zone issues (this should also be fixed, but that's more effort).

### What is the solution you are proposing?

Use only "days since" or "days until" for all of these values. 

### What alternatives have you considered?

Ignoring the times.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [X] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Could you try to replicate this on the demo site? I think I fixed this issue during some other date related improvements.

**Comment by hay-kot** [comment]
Closing since it's fixed in main (at least i believe that it is), will be in next release. Thanks!
