### ISSUE TITLE
Ability to add order numbers to an item

### ISSUE THREAD

**Issue by Dxvxdffm** [hay-kot/homebox#84]
### What is the problem you are trying to solve with this feature?

It would be pretty useful to add order numbers to an item.

### What is the solution you are proposing?

A new field on the page of the item within the "Purchase" box. Maybe under the "Purchase from" field.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! The next release will support arbitrary text fields for items. I think that this would fall into the scope of those custom fields.

![image](https://user-images.githubusercontent.com/64056131/196020129-62a2a5cb-493a-4024-952e-1ecd3f41b0e7.png)
