### ISSUE TITLE
Exclude non-images from thumbnail generation

### ISSUE THREAD

**Issue by danielrosehill** [hay-kot/homebox#842]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

e8449b3a7363a6cfd5bc6151609e6d2d94b4f7d8

### What is the issue you are experiencing?

Currently if there are a mix of images and non-images as attachments for an asset (for example a PDF and an image) Homebox will not exclude the non-images from thumbnail generation. This can result in a broken image thumbnail appearing for the asset even when a valid photo exists. 
 
![2024-03-08_18-16](https://github.com/hay-kot/homebox/assets/40233203/35d6b571-fa47-41d9-a3b2-c728eed86161)
![2024-03-08_18-16_1](https://github.com/hay-kot/homebox/assets/40233203/cc2a1545-94e7-4d10-bc88-ee3bc4956613)
![2024-03-08_18-16_2](https://github.com/hay-kot/homebox/assets/40233203/37ab3d7f-e62e-4025-a6bc-7d8cf6594efb)

### How can the maintainer reproduce the issue?

1. Create an asset.
2. Add a PDF and then an image.
3. Homebox will give a broken thumbnail image.

### Deployment

Docker (Synology)

### Deployment Details

Synology / LAN.

**Comment by danielrosehilljlm** [comment]
Daniel's stupidity (I uploaded an attachment to photos by mistake. Adding it to the right "placeholder" has resolved the behavior)
