### ISSUE TITLE
Can't remove labels

### ISSUE THREAD

**Issue by danielrosehill** [hay-kot/homebox#847]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

e8449b3a7363a6cfd5bc6151609e6d2d94b4f7d8

### What is the issue you are experiencing?

Once I add a label to an item, I can't remove it

### How can the maintainer reproduce the issue?

Create an asset, add a label, then try to use backspace to delete the label 

### Deployment

Docker (Synology)

Details about client:

Chrome on Ubuntu 22.04

**Comment by hay-kot** [comment]
You can click the item again to toggle it 

![CleanShot 2024-03-12 at 17 43 27@2x](https://github.com/hay-kot/homebox/assets/64056131/19f7a02a-7110-4fa7-b8f7-be3e6e8369b5)

**Comment by hay-kot** [comment]
Closing, feel free to re-open if the comment above doesn't solve your issue.

**Comment by Battmain** [comment]
I'm having this issue as well. I'm running Homebox in docker on a Synology NAS as well, but accessing it on Windows 10 in Firefox.
