### ISSUE TITLE
Add custom wallpapers to homepage

### ISSUE THREAD

**Issue by NWalen** [hay-kot/homebox#851]
### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't something I'm going to implement, it's possible I would merge a PR with this change, but since it's not on my radar I'm going to close this issue. Thanks!
