### ISSUE TITLE
Full breadcrumbs for assets

### ISSUE THREAD

**Issue by danielrosehill** [hay-kot/homebox#863]
### What is the problem you are trying to solve with this feature?

Currently if you have a "child-child" asset the breadcrumb navigation will only show you two levels. 

To give an example of when this is problematic, here's my current system:

Shelf number in my cabinet (asset)
A box (a child asset)
An item (a child-child asset)

It would be very useful if I could call up an item (child-child asset) and get a breadcrumb that could show me the first level of the hierarchy at a glance:

![breadcrumb](https://github.com/hay-kot/homebox/assets/40233203/aaceb622-0ca1-4684-959e-8d65271335a5)

Curren

### What is the solution you are proposing?

Full breadcrumbs on assets that are nested beyond the second degree

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This has been added in nightly so it will be in the next release

![CleanShot 2024-03-30 at 17 20 04@2x](https://github.com/hay-kot/homebox/assets/64056131/e6456a3a-7a4a-40e8-8138-8ea284e68476)
