### ISSUE TITLE
Add quantity to cards

### ISSUE THREAD

**Issue by Th3M1k3y** [hay-kot/homebox#870]
### What is the problem you are trying to solve with this feature?

Easier notice if I am out of stock of something without looking at each item.

### What is the solution you are proposing?

Adding quantity to cards, just like labels are shown.

### What alternatives have you considered?

An overlay on the image showing either quantity or just the quantity is zero.

### Additional context

In this example I have set the black abs to zero, but it isn't clearly visible I don't have any of it left.

![image](https://github.com/hay-kot/homebox/assets/29869794/7db16746-49a6-4f5d-bad9-1b15ab2133c6)

Same issue when accessing a label, but here there is the option to show it as a table, but it would still be nice if it would show quantity on the card here too.

![image](https://github.com/hay-kot/homebox/assets/29869794/ec43a087-106a-4972-a0d8-d14a7e641373)

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Quantities do display on cards

![CleanShot 2024-03-31 at 20 53 23@2x](https://github.com/hay-kot/homebox/assets/64056131/31a333d1-6f47-4559-a61c-3b29f8abbeee)


Is it the theme?

**Comment by Th3M1k3y** [comment]
I just tested a few, including the Homebox theme, also tried in firefox, quantity isn't showing. Do I need to enable it somewhere?

**Comment by Th3M1k3y** [comment]
I just noticed, if I set quantity to 2 or more, it will show up. But setting it to 1 or 0 and it isn't showing anything.

Using this Version: v0.10.3 ~ Build: e8449b3a7363a6cfd5bc6151609e6d2d94b4f7d8

**Comment by hay-kot** [comment]
Ahhhh. Looks like I changed the behavior

https://github.com/hay-kot/homebox/commit/27b72603e12542eacf18224937701026e9542522

Should be fixed in the next release then.

**Comment by hay-kot** [comment]
Closing since it's fixed in main, will be in next release. Thanks!
