### ISSUE TITLE
Per-Location Invite?

### ISSUE THREAD

**Issue by mikeperalta1** [hay-kot/homebox#871]
### What is the problem you are trying to solve with this feature?

It would be nice to have finer control over location sharing. I would like to maintain control of my main account's locations but for specific locations.

For example, two people living in the same home might each want to manage their own bedrooms to retain control and privacy. But they might both want to manage common areas together.

### What is the solution you are proposing?

Two possible ideas so far:

1. Per-Location invite links
2. A permissions area for each location, where you can select/check other users to receive read and/or write access to your locations.

### What alternatives have you considered?

I was thinking of making a separate account for the common areas and having it invite each personal account.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't something I'm going to implement, I don't have the time to implement the fine grained access control required for this. Thanks for the interest!
